/* Audio-clock look-ahead sequencer; original synthesis; PCM WAV and standard MIDI output. */
(function(D){'use strict';const S=D.Studio,A=S.Audio={};A.frequency=midi=>440*2**((midi-69)/12);const noiseCache=new WeakMap();
function noise(context){if(noiseCache.has(context))return noiseCache.get(context);const buffer=context.createBuffer(1,context.sampleRate,context.sampleRate),data=buffer.getChannelData(0);let seed=0x43abc123;for(let i=0;i<data.length;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;data[i]=seed/2147483648-1;}noiseCache.set(context,buffer);return buffer;}
A.graph=(context,model,masterVolume=1)=>{const master=context.createGain(),compressor=context.createDynamicsCompressor();master.gain.value=masterVolume*.65;compressor.threshold.value=-12;compressor.knee.value=12;compressor.ratio.value=5;master.connect(compressor);compressor.connect(context.destination);return{master,compressor};};
A.voice=(context,output,track,time,velocity=1,overrides={})=>{const kind=track.kind,midi=overrides.pitch??track.pitch??48,gain=context.createGain(),pan=context.createStereoPanner(),filter=context.createBiquadFilter();gain.gain.setValueAtTime(.0001,time);pan.pan.value=S.finite(track.pan,0,-1,1);filter.type='lowpass';filter.frequency.value=S.finite(track.cutoff,8000,80,16000);gain.connect(filter);filter.connect(pan);pan.connect(output);const amplitude=S.finite(track.gain,.7,0,1)*velocity,voices=[];const release=(node,end)=>{node.start(time);node.stop(end);voices.push(node);node.onended=()=>{node.disconnect();if(voices.every(n=>n._done||n===node)){gain.disconnect();pan.disconnect();filter.disconnect();}node._done=true;};};const oscillator=(type,hz,end,volume=1)=>{const o=context.createOscillator();o.type=type;o.frequency.setValueAtTime(hz,time);if(volume!==1){const g=context.createGain();g.gain.value=volume;o.connect(g);g.connect(gain);o.addEventListener('ended',()=>g.disconnect());}else o.connect(gain);release(o,end);return o;};const envelope=(peak,attack,decay)=>{gain.gain.exponentialRampToValueAtTime(Math.max(.0002,peak),time+attack);gain.gain.exponentialRampToValueAtTime(.0001,time+decay);};if(kind==='kick'){const o=oscillator('sine',150,time+.5);o.frequency.exponentialRampToValueAtTime(42,time+.18);envelope(amplitude,.005,.47);}else if(kind==='snare'||kind==='hat'){const n=context.createBufferSource(),high=context.createBiquadFilter();n.buffer=noise(context);high.type='highpass';high.frequency.value=kind==='hat'?6500:1700;n.connect(high);high.connect(gain);const end=time+(kind==='hat'?.075:.20);release(n,end);n.addEventListener('ended',()=>high.disconnect());if(kind==='snare')oscillator('triangle',185,time+.15,.22);envelope(amplitude*(kind==='hat'?.35:.60),.002,end-time-.005);}else{const duration=kind==='chord'?.75:.32,root=A.frequency(midi);for(const interval of(kind==='chord'?[0,4,7]:[0]))oscillator(kind==='bass'?'triangle':kind==='lead'?'sawtooth':'sine',root*2**(interval/12),time+duration,kind==='chord'?.28:1);envelope(amplitude*(kind==='bass'?.8:.35),.015,duration-.02);}return voices;};
A.stepTime=(model,step)=>{const beat=60/model.bpm/4;return step*beat+(step%2?model.swing*beat*.5:0);};A.audible=(model,track)=>!track.mute&&(!model.tracks.some(t=>t.solo)||track.solo);
class Sequencer{constructor(model,onStep){this.model=model;this.onStep=onStep;this.context=null;this.timer=0;this.running=false;this.step=0;this.start=0;this.active=new Set();this.generation=0;this.disposed=false;}
async ensure(){if(this.disposed)throw Error('Audio instrument has been disposed.');if(!this.context){const C=globalThis.AudioContext||globalThis.webkitAudioContext;if(!C)throw Error('Web Audio is unavailable.');this.context=new C();this.graph=A.graph(this.context,this.model(),D.store.data.prefs.volume);this.analyser=this.context.createAnalyser();this.analyser.fftSize=512;this.graph.master.connect(this.analyser);}await this.context.resume();return this.context;}
async play(){if(this.running||this.disposed)return;const generation=++this.generation;await this.ensure();if(this.running||generation!==this.generation||this.disposed)return;this.running=true;this.step=0;this.start=this.context.currentTime+.06;const tick=()=>{if(!this.running||generation!==this.generation)return;const m=this.model();this.graph.master.gain.setTargetAtTime(D.store.data.prefs.volume*.65,this.context.currentTime,.02);let guard=0;while(this.start+A.stepTime(m,this.step)<this.context.currentTime+.10&&guard++<64){const time=this.start+A.stepTime(m,this.step),index=this.step%m.steps;if(time>=this.context.currentTime-.01)for(const track of m.tracks){const v=track.pattern[index]||0;if(v&&A.audible(m,track))this.schedule(track,Math.max(time,this.context.currentTime),v);}this.step++;}const elapsed=this.context.currentTime-this.start,beat=60/m.bpm/4;let current=Math.max(0,Math.floor(elapsed/beat));if(A.stepTime(m,current)>elapsed&&current>0)current--;this.onStep?.(current%m.steps);};tick();this.timer=setInterval(tick,25);}
schedule(track,time,velocity=1,overrides){for(const source of A.voice(this.context,this.graph.master,track,time,velocity,overrides)){this.active.add(source);source.addEventListener('ended',()=>this.active.delete(source));}}
async preview(track,pitch){const generation=this.generation;await this.ensure();if(generation!==this.generation||this.disposed)return;this.graph.master.gain.value=D.store.data.prefs.volume*.65;this.schedule(track,this.context.currentTime+.005,.9,{pitch});}
stop(){this.running=false;this.generation++;clearInterval(this.timer);for(const node of this.active){try{node.stop();}catch{}}this.active.clear();this.onStep?.(-1);}
async dispose(){this.stop();this.disposed=true;if(this.context&&this.context.state!=='closed')await this.context.close();this.context=null;}}
A.Sequencer=Sequencer;
A.render=async(model,bars=model.bars||4)=>{const seconds=A.stepTime(model,model.steps*bars)+1,rate=44100;if(seconds>130)throw Error('Audio export is limited to 130 seconds.');const C=globalThis.OfflineAudioContext||globalThis.webkitOfflineAudioContext;if(!C)throw Error('Offline audio rendering unavailable.');const context=new C(2,Math.ceil(seconds*rate),rate),graph=A.graph(context,model,1);for(let step=0;step<model.steps*bars;step++)for(const track of model.tracks){const velocity=track.pattern[step%model.steps]||0;if(velocity&&A.audible(model,track))A.voice(context,graph.master,track,A.stepTime(model,step)+.01,velocity);}return context.startRendering();};
A.wav=buffer=>{const channels=buffer.numberOfChannels,length=buffer.length,block=channels*2,dataSize=length*block,bytes=new Uint8Array(44+dataSize),v=new DataView(bytes.buffer);const str=(offset,s)=>{for(let i=0;i<s.length;i++)v.setUint8(offset+i,s.charCodeAt(i));};str(0,'RIFF');v.setUint32(4,36+dataSize,true);str(8,'WAVE');str(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,channels,true);v.setUint32(24,buffer.sampleRate,true);v.setUint32(28,buffer.sampleRate*block,true);v.setUint16(32,block,true);v.setUint16(34,16,true);str(36,'data');v.setUint32(40,dataSize,true);const arrays=Array.from({length:channels},(_,i)=>buffer.getChannelData(i));let p=44;for(let i=0;i<length;i++)for(let c=0;c<channels;c++){const sample=Math.max(-1,Math.min(1,arrays[c][i]));v.setInt16(p,Math.round(sample*(sample<0?32768:32767)),true);p+=2;}return bytes;};
A.midi=model=>{const tempo=Math.round(60e6/model.bpm),events=[{tick:0,data:[0xff,0x51,3,(tempo>>16)&255,(tempo>>8)&255,tempo&255]}],ticks=480,drums={kick:36,snare:38,hat:42};for(let step=0;step<model.steps*model.bars;step++)model.tracks.forEach((track,i)=>{const velocity=track.pattern[step%model.steps];if(!velocity||!A.audible(model,track))return;const isDrum=track.kind in drums,channel=isDrum?9:i%9,start=Math.round(A.stepTime(model,step)*model.bpm/60*ticks),notes=track.kind==='chord'?[0,4,7]:[0];for(const interval of notes){const note=Math.max(0,Math.min(127,isDrum?drums[track.kind]:track.pitch+interval));events.push({tick:start,data:[0x90|channel,note,Math.round(velocity*track.gain*110)]},{tick:start+(isDrum?60:100),data:[0x80|channel,note,0]});}});events.sort((a,b)=>a.tick-b.tick||(a.data[0]&0xf0)-(b.data[0]&0xf0));const variable=n=>{const a=[n&127];while(n>>=7)a.unshift((n&127)|128);return a;};const track=[];let previous=0;for(const event of events){track.push(...variable(event.tick-previous),...event.data);previous=event.tick;}track.push(0,0xff,0x2f,0);const length=track.length;return new Uint8Array([77,84,104,100,0,0,0,6,0,0,0,1,1,224,77,84,114,107,length>>>24,(length>>>16)&255,(length>>>8)&255,length&255,...track]);};
})(window.Duo);
