/* Deterministic geometry, matrix algebra, CAD interchange and polygon construction. */
(function(D){'use strict';const S=D.Studio,G=S.Geometry={},EPS=1e-8;
G.add=(a,b)=>a.map((v,i)=>v+b[i]);G.sub=(a,b)=>a.map((v,i)=>v-b[i]);G.dot=(a,b)=>a.reduce((v,x,i)=>v+x*b[i],0);G.cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];G.normal=v=>{const n=Math.hypot(...v)||1;return v.map(x=>x/n);};
G.identity=()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);G.multiply=(a,b)=>{const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;};G.transform=(m,p)=>{const q=[p[0],p[1],p[2],p[3]??1];return[0,1,2,3].map(r=>q.reduce((s,v,k)=>s+m[k*4+r]*v,0));};
G.perspective=(fov,aspect,near=.05,far=200)=>{const f=1/Math.tan(fov/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,far*nf,-1,0,0,far*near*nf,0]);};G.lookAt=(eye,target,up=[0,1,0])=>{const z=G.normal(G.sub(eye,target)),x=G.normal(G.cross(up,z)),y=G.cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-G.dot(x,eye),-G.dot(y,eye),-G.dot(z,eye),1]);};
G.inverse=m=>{const a=Array.from({length:4},(_,r)=>[...Array.from({length:4},(_,c)=>m[c*4+r]),...Array.from({length:4},(_,c)=>c===r?1:0)]);for(let c=0;c<4;c++){let pivot=c;for(let r=c+1;r<4;r++)if(Math.abs(a[r][c])>Math.abs(a[pivot][c]))pivot=r;if(Math.abs(a[pivot][c])<EPS)return null;[a[c],a[pivot]]=[a[pivot],a[c]];const d=a[c][c];a[c]=a[c].map(v=>v/d);for(let r=0;r<4;r++)if(r!==c){const k=a[r][c];a[r]=a[r].map((v,j)=>v-k*a[c][j]);}}return new Float32Array(Array.from({length:16},(_,i)=>a[i%4][Math.floor(i/4)+4]));};
G.model=o=>{const[rx,ry,rz]=(o.rotation||[0,0,0]).map(v=>v*Math.PI/180),[sx,sy,sz]=o.scale||[1,1,1],[x,y,z]=o.position||[0,0,0],cx=Math.cos(rx),ax=Math.sin(rx),cy=Math.cos(ry),ay=Math.sin(ry),cz=Math.cos(rz),az=Math.sin(rz);const X=new Float32Array([1,0,0,0,0,cx,ax,0,0,-ax,cx,0,0,0,0,1]),Y=new Float32Array([cy,0,-ay,0,0,1,0,0,ay,0,cy,0,0,0,0,1]),Z=new Float32Array([cz,az,0,0,-az,cz,0,0,0,0,1,0,0,0,0,1]),T=G.identity();T[0]=sx;T[5]=sy;T[10]=sz;const R=G.multiply(Z,G.multiply(Y,G.multiply(X,T)));R[12]=x;R[13]=y;R[14]=z;return R;};
G.camera=(camera,aspect)=>{const yaw=S.finite(camera.yaw,.65),pitch=S.finite(camera.pitch,.4,-1.45,1.45),distance=S.finite(camera.distance,6,1,80),target=camera.target||[0,0,0],eye=G.add(target,[distance*Math.cos(pitch)*Math.sin(yaw),distance*Math.sin(pitch),distance*Math.cos(pitch)*Math.cos(yaw)]);return{eye,matrix:G.multiply(G.perspective(Math.PI/4,aspect),G.lookAt(eye,target))};};
G.box=()=>({vertices:[[-.5,-.5,-.5],[.5,-.5,-.5],[.5,.5,-.5],[-.5,.5,-.5],[-.5,-.5,.5],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5]],faces:[[0,2,1],[0,3,2],[4,5,6],[4,6,7],[0,1,5],[0,5,4],[3,7,6],[3,6,2],[0,4,7],[0,7,3],[1,2,6],[1,6,5]]});
G.sphere=(segments=24,rings=16)=>{const vertices=[],faces=[];for(let j=0;j<=rings;j++)for(let i=0;i<=segments;i++){const p=Math.PI*j/rings,t=Math.PI*2*i/segments;vertices.push([Math.sin(p)*Math.cos(t)*.5,Math.cos(p)*.5,Math.sin(p)*Math.sin(t)*.5]);}for(let j=0;j<rings;j++)for(let i=0;i<segments;i++){const a=j*(segments+1)+i,b=a+segments+1;if(j)faces.push([a,b,a+1]);if(j<rings-1)faces.push([a+1,b,b+1]);}return{vertices,faces};};
G.torus=(segments=36,rings=12)=>{const vertices=[],faces=[];for(let i=0;i<segments;i++)for(let j=0;j<rings;j++){const u=2*Math.PI*i/segments,v=2*Math.PI*j/rings,r=.65+.22*Math.cos(v);vertices.push([r*Math.cos(u),.22*Math.sin(v),r*Math.sin(u)]);}for(let i=0;i<segments;i++)for(let j=0;j<rings;j++){const a=i*rings+j,b=((i+1)%segments)*rings+j,c=((i+1)%segments)*rings+(j+1)%rings,d=i*rings+(j+1)%rings;faces.push([a,d,b],[b,d,c]);}return{vertices,faces};};
G.lathe=(profile,segments=32)=>{segments=Math.round(S.finite(segments,32,3,128));const vertices=[],faces=[];for(let i=0;i<segments;i++){const t=i*2*Math.PI/segments;for(const p of profile)vertices.push([p[0]*Math.cos(t),p[1],p[0]*Math.sin(t)]);}const n=profile.length;for(let i=0;i<segments;i++)for(let j=0;j<n-1;j++){const a=i*n+j,b=((i+1)%segments)*n+j;faces.push([a,a+1,b],[b,a+1,b+1]);}return{vertices,faces};};
G.area=points=>points.reduce((s,p,i)=>{const q=points[(i+1)%points.length];return s+p[0]*q[1]-q[0]*p[1];},0)/2;
G.triangulate=points=>{if(points.length<3)return[];const ccw=G.area(points)>0,ids=points.map((_,i)=>i);if(!ccw)ids.reverse();const faces=[],cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]),inside=(p,a,b,c)=>cross(a,b,p)>=-EPS&&cross(b,c,p)>=-EPS&&cross(c,a,p)>=-EPS;let guard=points.length*points.length;while(ids.length>3&&guard--){let clipped=false;for(let i=0;i<ids.length;i++){const a=ids[(i+ids.length-1)%ids.length],b=ids[i],c=ids[(i+1)%ids.length];if(cross(points[a],points[b],points[c])<=EPS)continue;if(ids.some(k=>k!==a&&k!==b&&k!==c&&inside(points[k],points[a],points[b],points[c])))continue;faces.push([a,b,c]);ids.splice(i,1);clipped=true;break;}if(!clipped)throw Error('Profile must be a simple, non-self-intersecting polygon.');}if(ids.length===3)faces.push(ids.slice());return faces;};
G.extrude=(points,depth=1,twist=0,levels=12)=>{const polygon=G.area(points)>0?points:points.slice().reverse(),caps=G.triangulate(polygon),vertices=[],faces=[],n=polygon.length;for(let j=0;j<=levels;j++){const t=j/levels*twist*Math.PI/180,c=Math.cos(t),s=Math.sin(t);for(const[x,y]of polygon)vertices.push([x*c-y*s,y*c+x*s,depth*(j/levels-.5)]);}for(let j=0;j<levels;j++)for(let i=0;i<n;i++){const a=j*n+i,b=j*n+(i+1)%n,c=b+n,d=a+n;faces.push([a,b,c],[a,c,d]);}for(const[a,b,c]of caps)faces.push([c,b,a],[a+levels*n,b+levels*n,c+levels*n]);return{vertices,faces};};
G.validateMesh=mesh=>{if(!mesh||!Array.isArray(mesh.vertices)||!Array.isArray(mesh.faces)||mesh.vertices.length>20000||mesh.faces.length>40000)throw Error('Mesh limits: 20,000 vertices / 40,000 triangles.');mesh.vertices.forEach(v=>{if(!Array.isArray(v)||v.length!==3||!v.every(x=>Number.isFinite(x)&&Math.abs(x)<1e6))throw Error('Invalid mesh coordinate.');});mesh.faces.forEach(f=>{if(!Array.isArray(f)||f.length!==3||!f.every(i=>Number.isInteger(i)&&i>=0&&i<mesh.vertices.length))throw Error('Invalid face index.');});return mesh;};
const cache=new Map();G.primitive=type=>{if(cache.has(type))return cache.get(type);let mesh;switch(type){case'sphere':mesh=G.sphere();break;case'torus':mesh=G.torus();break;case'cylinder':mesh=G.lathe([[0,-.5],[.5,-.5],[.5,.5],[0,.5]]);break;case'cone':mesh=G.lathe([[0,-.5],[.5,-.5],[0,.5]]);break;default:mesh=G.box();}cache.set(type,mesh);return mesh;};
G.world=o=>{const mesh=G.validateMesh(o.mesh||G.primitive(o.type)),m=G.model(o);return{vertices:mesh.vertices.map(p=>G.transform(m,p).slice(0,3)),faces:mesh.faces};};
G.rayTriangle=(origin,direction,a,b,c)=>{const ab=G.sub(b,a),ac=G.sub(c,a),p=G.cross(direction,ac),det=G.dot(ab,p);if(Math.abs(det)<EPS)return Infinity;const inv=1/det,t=G.sub(origin,a),u=G.dot(t,p)*inv;if(u<0||u>1)return Infinity;const q=G.cross(t,ab),v=G.dot(direction,q)*inv;if(v<0||u+v>1)return Infinity;const distance=G.dot(ac,q)*inv;return distance>EPS?distance:Infinity;};
G.obj=objects=>{let out='# Duo Studio OBJ · baked world transforms\n',offset=1;for(const object of objects){if(object.visible===false)continue;const mesh=G.world(object);out+='o '+String(object.name||'Object').replace(/[^a-zA-Z0-9_-]/g,'_')+'\n';out+=mesh.vertices.map(v=>'v '+v.map(n=>n.toFixed(6)).join(' ')).join('\n')+'\n';out+=mesh.faces.map(f=>'f '+f.map(i=>i+offset).join(' ')).join('\n')+'\n';offset+=mesh.vertices.length;}return out;};
G.parseOBJ=text=>{const vertices=[],faces=[];if(text.length>8e6)throw Error('OBJ exceeds 8 MB.');for(const line of text.split(/\r?\n/)){const[type,...parts]=line.trim().split(/\s+/);if(type==='v')vertices.push(parts.slice(0,3).map(Number));else if(type==='f'){const face=parts.map(x=>{const i=Number(x.split('/')[0]);return i<0?vertices.length+i:i-1;});for(let i=1;i<face.length-1;i++)faces.push([face[0],face[i],face[i+1]]);}if(vertices.length>20000||faces.length>40000)throw Error('OBJ complexity limit exceeded.');}if(!vertices.length||!faces.length)throw Error('OBJ has no triangle geometry.');return G.validateMesh({vertices,faces});};
G.stl=objects=>{let out='solid duo_studio\n';for(const object of objects){if(object.visible===false)continue;const mesh=G.world(object);for(const face of mesh.faces){const[a,b,c]=face.map(i=>mesh.vertices[i]),n=G.normal(G.cross(G.sub(b,a),G.sub(c,a)));if(Math.hypot(...G.cross(G.sub(b,a),G.sub(c,a)))<EPS)continue;out+='facet normal '+n.join(' ')+'\n outer loop\n'+[a,b,c].map(v=>'  vertex '+v.join(' ')).join('\n')+'\n endloop\nendfacet\n';}}return out+'endsolid duo_studio\n';};
G.distanceToSegment=(p,a,b)=>{const dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1)));return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy);};
G.CAD={length(e){if(e.type==='circle')return 2*Math.PI*Math.abs(e.r||0);if(e.type==='rect')return 2*(Math.abs(e.w||0)+Math.abs(e.h||0));return Math.hypot((e.x2??e.x)-e.x,(e.y2??e.y)-e.y);},dxf(entities){let s='0\nSECTION\n2\nHEADER\n9\n$ACADVER\n1\nAC1027\n9\n$INSUNITS\n70\n4\n0\nENDSEC\n0\nSECTION\n2\nENTITIES\n';const pair=(k,v)=>k+'\n'+v+'\n';function base(e,type){return pair(0,type)+pair(8,String(e.layer||'0').replace(/[\r\n]/g,''))+pair(420,parseInt(S.color(e.color).slice(1),16));}function line(e,x,y,x2,y2){return base(e,'LINE')+pair(10,x)+pair(20,-y)+pair(30,0)+pair(11,x2)+pair(21,-y2)+pair(31,0);}for(const e of entities){if(e.type==='line'||e.type==='dimension')s+=line(e,e.x,e.y,e.x2,e.y2);if(e.type==='circle')s+=base(e,'CIRCLE')+pair(10,e.x)+pair(20,-e.y)+pair(30,0)+pair(40,e.r);if(e.type==='rect')s+=line(e,e.x,e.y,e.x+e.w,e.y)+line(e,e.x+e.w,e.y,e.x+e.w,e.y+e.h)+line(e,e.x+e.w,e.y+e.h,e.x,e.y+e.h)+line(e,e.x,e.y+e.h,e.x,e.y);if(e.type==='text')s+=base(e,'TEXT')+pair(10,e.x)+pair(20,-e.y)+pair(40,e.size||12)+pair(1,String(e.text||'').replace(/[\r\n]/g,' '));}return s+'0\nENDSEC\n0\nEOF\n';},
parseDXF(text){if(text.length>8e6)throw Error('DXF exceeds 8 MB.');const lines=text.split(/\r?\n/),entities=[];let current=null,active=false,unsupported=new Set();function emit(){if(!current||!active)return;const get=(k,d=0)=>S.finite(current.values[k],d),e={id:D.uid(),x:get(10),y:-get(20),color:current.values[420]?'#'+Math.round(S.finite(current.values[420],0,0,16777215)).toString(16).padStart(6,'0'):'#a3c6ff',layer:current.values[8]||'Imported'};switch(current.type){case'LINE':Object.assign(e,{type:'line',x2:get(11),y2:-get(21)});break;case'CIRCLE':Object.assign(e,{type:'circle',r:Math.abs(get(40,10))});break;case'TEXT':Object.assign(e,{type:'text',text:current.values[1]||'',size:get(40,12)});break;default:if(!['ENDSEC','EOF'].includes(current.type))unsupported.add(current.type);return;}entities.push(e);if(entities.length>2000)throw Error('DXF exceeds 2,000 supported entities.');}for(let i=0;i+1<lines.length;i+=2){const code=Number(lines[i]),value=lines[i+1].trim();if(code===0){emit();if(value==='ENDSEC')active=false;current={type:value,values:{}};}else if(code===2&&current?.type==='SECTION')active=value==='ENTITIES';else if(current)current.values[code]=value;}emit();return{entities,unsupported:[...unsupported]};},
svg(entities){return`<svg xmlns="http://www.w3.org/2000/svg" viewBox="-500 -350 1000 700">${entities.map(e=>{const c=S.color(e.color);switch(e.type){case'circle':return`<circle cx="${e.x}" cy="${e.y}" r="${e.r}" stroke="${c}" fill="none"/>`;case'rect':return`<rect x="${Math.min(e.x,e.x+e.w)}" y="${Math.min(e.y,e.y+e.h)}" width="${Math.abs(e.w)}" height="${Math.abs(e.h)}" stroke="${c}" fill="none"/>`;case'text':return`<text x="${e.x}" y="${e.y}" fill="${c}" font-family="sans-serif" font-size="${e.size||12}">${D.escape(e.text)}</text>`;default:return`<path d="M${e.x} ${e.y}L${e.x2} ${e.y2}" stroke="${c}" fill="none"/>`;}}).join('')}</svg>`;}};
})(window.Duo);
