/* WebGPU triangle/edge renderer. Shared GPU device; per-view resources; honest software fallback. */
(function(D){'use strict';const S=D.Studio,G=S.Geometry;
const shader=`
struct Camera { viewProjection: mat4x4f };
@group(0) @binding(0) var<uniform> camera: Camera;
struct Input { @location(0) position: vec3f, @location(1) normal: vec3f, @location(2) color: vec4f };
struct Output { @builtin(position) position: vec4f, @location(0) normal: vec3f, @location(1) color: vec4f };
@vertex fn vertex(input: Input) -> Output { var result: Output; result.position=camera.viewProjection*vec4f(input.position,1.0);result.normal=input.normal;result.color=input.color;return result; }
@fragment fn fragment(input: Output) -> @location(0) vec4f {let normal=normalize(input.normal+vec3f(0.00001));let light=max(dot(normal,normalize(vec3f(0.4,0.8,0.6))),0.0);let rim=max(dot(normal,normalize(vec3f(-0.7,0.2,-0.4))),0.0);let tone=input.color.rgb*(0.24+light*0.70)+vec3f(0.12,0.15,0.22)*rim;return vec4f(tone,input.color.a);}
@fragment fn lineFragment(input: Output) -> @location(0) vec4f {return input.color;}
`;
let sharedDevice=null;async function acquireDevice(){if(sharedDevice)return sharedDevice;sharedDevice=(async()=>{if(!isSecureContext||!navigator.gpu)throw Error('WebGPU unavailable in this context');const adapter=await navigator.gpu.requestAdapter({powerPreference:'high-performance'});if(!adapter)throw Error('No GPU adapter');const device=await adapter.requestDevice();device.lost.then(()=>{sharedDevice=null;});return device;})();try{return await sharedDevice;}catch(e){sharedDevice=null;throw e;}}
const rgb=hex=>{const n=parseInt(S.color(hex).slice(1),16);return[(n>>16&255)/255,(n>>8&255)/255,(n&255)/255,1];};
class View3D{
constructor(host,scope,{camera,onCamera,onPick}={}){this.host=host;this.scope=D.scope();scope?.cleanup(()=>this.dispose());this.camera=camera||{yaw:.7,pitch:.45,distance:7,target:[0,0,0]};this.onCamera=onCamera;this.onPick=onPick;this.objects=[];this.world=[];this.selected='';this.wire=false;this.disposed=false;this.frame=0;this.backend='Canvas 2D';this.fallback=document.createElement('canvas');this.fallback.className='pro-canvas';this.g=this.fallback.getContext('2d',{alpha:false});this.canvas=document.createElement('canvas');this.canvas.className='pro-canvas gpu-scene';this.canvas.hidden=true;host.append(this.fallback,this.canvas);host.tabIndex=0;host.setAttribute('aria-label','3D viewport. Drag to orbit, Shift drag to pan, wheel to zoom.');this.badge=document.createElement('span');this.badge.className='viewport-badge';host.append(this.badge);this.ro=new ResizeObserver(()=>this.invalidate());this.ro.observe(host);this.bindInput();this.initGPU();this.invalidate();}
async initGPU(){try{const device=this.device=await acquireDevice();if(this.disposed)return;const context=this.context=this.canvas.getContext('webgpu');if(!context)throw Error('No WebGPU canvas context');this.format=navigator.gpu.getPreferredCanvasFormat();context.configure({device,format:this.format,alphaMode:'opaque'});const module=device.createShaderModule({label:'Duo Studio modeling shader',code:shader});const compilation=await module.getCompilationInfo(),errors=compilation.messages.filter(x=>x.type==='error');if(errors.length)throw Error(errors.map(x=>x.message).join('; '));if(this.disposed)return;device.pushErrorScope('validation');const vertex={module,entryPoint:'vertex',buffers:[{arrayStride:40,attributes:[{shaderLocation:0,offset:0,format:'float32x3'},{shaderLocation:1,offset:12,format:'float32x3'},{shaderLocation:2,offset:24,format:'float32x4'}]}]};this.pipeline=device.createRenderPipeline({label:'Duo solid geometry',layout:'auto',vertex,fragment:{module,entryPoint:'fragment',targets:[{format:this.format}]},primitive:{topology:'triangle-list',cullMode:'none'},depthStencil:{format:'depth24plus',depthWriteEnabled:true,depthCompare:'less'}});this.linePipeline=device.createRenderPipeline({label:'Duo mesh edges',layout:'auto',vertex,fragment:{module,entryPoint:'lineFragment',targets:[{format:this.format}]},primitive:{topology:'line-list'},depthStencil:{format:'depth24plus',depthWriteEnabled:false,depthCompare:'less-equal'}});this.uniform=device.createBuffer({size:64,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});this.bind=device.createBindGroup({layout:this.pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this.uniform}}]});this.lineBind=device.createBindGroup({layout:this.linePipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this.uniform}}]});const err=await device.popErrorScope();if(err)throw err;if(this.disposed){this.uniform.destroy();return;}this.backend='WebGPU';this.canvas.hidden=false;this.fallback.hidden=true;this.geometryDirty=true;device.addEventListener('uncapturederror',e=>this.useFallback(e.error.message),{signal:this.scope.signal});device.lost.then(info=>{if(!this.disposed)this.useFallback(info.message||'Device lost');});this.invalidate();}catch(e){this.useFallback(e.message);}}
useFallback(reason){if(this.disposed)return;this.backend='Canvas 2D';this.reason=reason;this.canvas.hidden=true;this.fallback.hidden=false;this.context?.unconfigure?.();this.vertexBuffer?.destroy();this.lineBuffer?.destroy();this.depth?.destroy();this.uniform?.destroy();this.vertexBuffer=this.lineBuffer=this.depth=this.uniform=null;this.invalidate();}
setObjects(objects,selected='',wire=false){this.objects=objects;this.selected=selected;this.wire=wire;this.world=objects.filter(o=>o.visible!==false).map(o=>({...G.world(o),color:o.color||'#91aaff',id:o.id,name:o.name}));this.geometryDirty=true;this.invalidate();}updateCamera(camera){this.camera=camera;this.invalidate();}invalidate(){if(!this.disposed&&!this.frame)this.frame=requestAnimationFrame(()=>{this.frame=0;this.draw();});}
resize(){const w=Math.max(1,this.host.clientWidth),h=Math.max(1,this.host.clientHeight),dpr=Math.min(devicePixelRatio||1,2);this.width=w;this.height=h;const max=this.device?.limits.maxTextureDimension2D||8192,pw=Math.min(max,Math.max(1,Math.round(w*dpr))),ph=Math.min(max,Math.max(1,Math.round(h*dpr)));if(this.canvas.width!==pw||this.canvas.height!==ph){this.canvas.width=this.fallback.width=pw;this.canvas.height=this.fallback.height=ph;this.depth?.destroy();this.depth=null;}this.g.setTransform(pw/w,0,0,ph/h,0,0);if(this.backend==='WebGPU'&&!this.depth)this.depth=this.device.createTexture({size:[pw,ph],format:'depth24plus',usage:GPUTextureUsage.RENDER_ATTACHMENT});}
project(p){const q=G.transform(this.matrix,p);return{x:(q[0]/q[3]*.5+.5)*this.width,y:(-.5*q[1]/q[3]+.5)*this.height,z:q[2]/q[3],w:q[3]};}
upload(){if(!this.geometryDirty)return;const triangles=[],lines=[];let count=0;const add=(a,p,n,c)=>a.push(...p,...n,...c);for(const o of this.world){const color=rgb(o.color);for(const face of o.faces){const[a,b,c]=face.map(i=>o.vertices[i]),normal=G.normal(G.cross(G.sub(b,a),G.sub(c,a)));for(const p of[a,b,c])add(triangles,p,normal,color);count++;if(this.wire||o.id===this.selected){const ink=o.id===this.selected?[.96,.80,.38,1]:[.30,.49,.66,1];for(const p of[a,b,b,c,c,a])add(lines,p,normal,ink);}}}for(let i=-10;i<=10;i++){const c=i===0?[.42,.45,.57,1]:[.16,.20,.29,1];for(const p of[[i,-1,-10],[i,-1,10],[-10,-1,i],[10,-1,i]])add(lines,p,[0,1,0],c);}this.triangleCount=count;this.vertexCount=triangles.length/10;this.lineCount=lines.length/10;const allocate=(name,data)=>{const bytes=new Float32Array(data);if(!this[name]||this[name].size<bytes.byteLength){this[name]?.destroy();this[name]=this.device.createBuffer({size:Math.max(40,Math.ceil(bytes.byteLength/256)*256),usage:GPUBufferUsage.VERTEX|GPUBufferUsage.COPY_DST});}if(bytes.byteLength)this.device.queue.writeBuffer(this[name],0,bytes);};allocate('vertexBuffer',triangles);allocate('lineBuffer',lines);this.geometryDirty=false;}
drawGPU(){this.upload();this.device.queue.writeBuffer(this.uniform,0,this.matrix);const encoder=this.device.createCommandEncoder({label:'Duo modeling frame'}),pass=encoder.beginRenderPass({colorAttachments:[{view:this.context.getCurrentTexture().createView(),loadOp:'clear',storeOp:'store',clearValue:{r:.035,g:.047,b:.074,a:1}}],depthStencilAttachment:{view:this.depth.createView(),depthLoadOp:'clear',depthStoreOp:'store',depthClearValue:1}});if(this.vertexCount&&!this.wire){pass.setPipeline(this.pipeline);pass.setBindGroup(0,this.bind);pass.setVertexBuffer(0,this.vertexBuffer);pass.draw(this.vertexCount);}if(this.lineCount){pass.setPipeline(this.linePipeline);pass.setBindGroup(0,this.lineBind);pass.setVertexBuffer(0,this.lineBuffer);pass.draw(this.lineCount);}pass.end();this.device.queue.submit([encoder.finish()]);}
drawSoftware(){const g=this.g,w=this.width,h=this.height;g.fillStyle='#0a0e17';g.fillRect(0,0,w,h);g.lineWidth=.8;for(let i=-10;i<=10;i++){g.strokeStyle=i===0?'#3a4257':'#20283b';for(const[a,b]of[[[i,-1,-10],[i,-1,10]],[[-10,-1,i],[10,-1,i]]]){const p=this.project(a),q=this.project(b);if(p.w<=.05||q.w<=.05)continue;g.beginPath();g.moveTo(p.x,p.y);g.lineTo(q.x,q.y);g.stroke();}}const list=[];for(const o of this.world){const points=o.vertices.map(p=>this.project(p));for(const f of o.faces){const p=f.map(i=>points[i]);if(p.some(q=>q.w<=.05||q.z>1))continue;const[a,b,c]=f.map(i=>o.vertices[i]),n=G.normal(G.cross(G.sub(b,a),G.sub(c,a))),light=.24+Math.max(0,G.dot(n,G.normal([.4,.8,.6])))*.70;list.push({p,z:p.reduce((s,v)=>s+v.z,0)/3,color:rgb(o.color).slice(0,3).map(v=>Math.round(v*255*light)),selected:o.id===this.selected});}}list.sort((a,b)=>b.z-a.z);this.triangleCount=list.length;for(const t of list){g.beginPath();g.moveTo(t.p[0].x,t.p[0].y);g.lineTo(t.p[1].x,t.p[1].y);g.lineTo(t.p[2].x,t.p[2].y);g.closePath();if(!this.wire){g.fillStyle=`rgb(${t.color.join(',')})`;g.fill();}if(this.wire||t.selected){g.strokeStyle=t.selected?'#f5cc65':'#607aa0';g.lineWidth=t.selected?.9:.6;g.stroke();}}}
draw(){if(this.disposed||!this.host.isConnected)return;this.resize();this.matrix=G.camera(this.camera,this.width/this.height).matrix;try{if(this.backend==='WebGPU')this.drawGPU();else this.drawSoftware();}catch(e){this.useFallback(e.message);}this.badge.textContent=this.backend+' · '+(this.triangleCount||0).toLocaleString()+' triangles';this.badge.title=this.reason||'Orbit · pan · zoom · select';}
pick(x,y){if(!this.matrix)return'';const inv=G.inverse(this.matrix);if(!inv)return'';const p=G.transform(inv,[x/this.width*2-1,1-y/this.height*2,1,1]),eye=G.camera(this.camera,this.width/this.height).eye,direction=G.normal(G.sub(p.slice(0,3).map(v=>v/p[3]),eye));let best=Infinity,id='';for(const o of this.world)for(const face of o.faces){const t=G.rayTriangle(eye,direction,...face.map(i=>o.vertices[i]));if(t<best){best=t;id=o.id;}}return id;}
bindInput(){let start=null;const pointers=new Map();let pinch=0,wasPinch=false;const point=e=>{const r=this.host.getBoundingClientRect();return{x:(e.clientX-r.left)*(this.width||1)/(r.width||1),y:(e.clientY-r.top)*(this.height||1)/(r.height||1)};};this.scope.on(this.host,'pointerdown',e=>{if(e.target.closest('button'))return;e.preventDefault();this.host.focus();try{this.host.setPointerCapture(e.pointerId);}catch{}pointers.set(e.pointerId,point(e));if(pointers.size===1){start={point:point(e),camera:S.clone(this.camera),moved:0};wasPinch=false;}else if(pointers.size===2){const[a,b]=[...pointers.values()];pinch=Math.hypot(a.x-b.x,a.y-b.y);wasPinch=true;}});this.scope.on(this.host,'pointermove',e=>{if(!pointers.has(e.pointerId))return;const p=point(e);pointers.set(e.pointerId,p);if(pointers.size===2){const[a,b]=[...pointers.values()],next=Math.hypot(a.x-b.x,a.y-b.y);this.camera.distance=S.finite(this.camera.distance*(pinch/(next||1)),6,1,80);pinch=next;}else if(start&&!wasPinch){const dx=p.x-start.point.x,dy=p.y-start.point.y;start.moved=Math.hypot(dx,dy);if(e.shiftKey||(e.buttons&4)){const d=start.camera.distance*.0015;this.camera.target=[start.camera.target[0]-dx*d,start.camera.target[1]+dy*d,start.camera.target[2]];}else{this.camera.yaw=start.camera.yaw-dx*.008;this.camera.pitch=S.finite(start.camera.pitch+dy*.008,.4,-1.45,1.45);}}this.invalidate();});const end=e=>{const p=point(e);pointers.delete(e.pointerId);if(!pointers.size){if(start&&start.moved<5&&!wasPinch&&e.type==='pointerup')this.onPick?.(this.pick(p.x,p.y));start=null;this.onCamera?.(this.camera);}};for(const type of['pointerup','pointercancel','lostpointercapture'])this.scope.on(this.host,type,end);this.scope.on(this.host,'wheel',e=>{e.preventDefault();this.camera.distance=S.finite(this.camera.distance*Math.exp(e.deltaY*.001),6,1,80);this.onCamera?.(this.camera);this.invalidate();},{passive:false});this.scope.on(this.host,'keydown',e=>{const amount=e.shiftKey?.2:.08;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')this.camera.yaw-=amount;if(e.key==='ArrowRight')this.camera.yaw+=amount;if(e.key==='ArrowUp')this.camera.pitch=Math.min(1.45,this.camera.pitch+amount);if(e.key==='ArrowDown')this.camera.pitch=Math.max(-1.45,this.camera.pitch-amount);if(e.key==='+')this.camera.distance=Math.max(1,this.camera.distance*.9);if(e.key==='-')this.camera.distance=Math.min(80,this.camera.distance*1.1);this.onCamera?.(this.camera);this.invalidate();}});}
async snapshot(){if(this.backend==='WebGPU')this.draw();return S.downloadCanvas(this.backend==='WebGPU'?this.canvas:this.fallback,'duo-scene.png');}
dispose(){if(this.disposed)return;this.disposed=true;cancelAnimationFrame(this.frame);this.ro.disconnect();this.scope.dispose();this.context?.unconfigure?.();for(const b of[this.vertexBuffer,this.lineBuffer,this.uniform,this.depth])b?.destroy();this.canvas.remove();this.fallback.remove();this.badge.remove();}
}
S.View3D=View3D;S.sceneShader=shader;
})(window.Duo);
