/** Independent SDK contracts: deliberately no simulator, browser globals or DOM mocks. */
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import K, { State, Binding, Scope, Environment, UndoManager, batch, effect, computed, Text, VStack } from '../sdk/index.mjs';
const results=[];
async function check(test,action){try{await action();results.push({test,passed:true});console.log('PASS',test);}catch(error){results.push({test,passed:false,error:String(error)});console.error('FAIL',test,error);}}
await check('ESM and CommonJS expose the same independent runtime',()=>{assert.equal(createRequire(import.meta.url)('../sdk/duokit.js'),K);assert.equal(K.version,'3.0.0');assert.equal(typeof globalThis.document,'undefined');});
await check('State projected and mapped binding preserve sibling properties',()=>{const s=new State({x:1,y:2});s.projectedValue.map('x').wrappedValue=4;assert.deepEqual(s.wrappedValue,{x:4,y:2});});
await check('State subscriptions unsubscribe and ignore equal identity',()=>{const s=new State(0);let calls=0;const off=s.subscribe(()=>calls++);s.value=0;s.value=1;off();s.value=2;assert.equal(calls,1);});
await check('Nested batches coalesce dependent effects',()=>{const a=new State(1),b=new State(2);let calls=0,total;const off=effect(()=>{calls++;total=a.value+b.value;});batch(()=>{a.value=3;batch(()=>b.value=8);a.value=9;});assert.equal(total,17);assert.equal(calls,2);off();});
await check('Conditional dependencies detach when branch changes',()=>{const select=new State(true),a=new State(2),b=new State(5);let calls=0,value;const off=effect(()=>{calls++;value=select.value?a.value:b.value;});select.value=false;a.value=10;assert.equal(calls,2);assert.equal(value,5);b.value=9;assert.equal(value,9);off();assert.equal(select.listeners.size,0);});
await check('Computed binding is read-only and disposable',()=>{const s=new State(3),c=computed(()=>s.value*2);assert.equal(c.value,6);s.value=4;assert.equal(c.value,8);assert.throws(()=>c.value=5);c.dispose();s.value=10;assert.equal(c.value,8);});
await check('Constant bindings reject mutations by retaining original value',()=>{const b=Binding.constant(4);b.value=9;assert.equal(b.value,4);});
await check('Scopes cancel events and children once in reverse ownership order',()=>{const s=new Scope(),target=new EventTarget(),events=[];let calls=0;s.on(target,'test',()=>calls++);const child=s.child();s.cleanup(()=>events.push('first'));s.cleanup(()=>events.push('second'));target.dispatchEvent(new Event('test'));s.dispose();s.dispose();target.dispatchEvent(new Event('test'));assert.equal(calls,1);assert(child.signal.aborted);assert.deepEqual(events,['second','first']);});
await check('Owned timers cannot outlive a disposed scope',async()=>{const s=new Scope();let ran=false;s.timeout(()=>ran=true,5);s.dispose();await new Promise(r=>setTimeout(r,12));assert.equal(ran,false);});
await check('Environment children inherit then override reactive values',()=>{const parent=new Environment({colorScheme:'light'}),child=parent.child({scenePhase:'active'});let value;const off=effect(()=>value=child.get('colorScheme'));parent.set('colorScheme','dark');assert.equal(value,'dark');child.set('colorScheme','light');parent.set('colorScheme','dark');assert.equal(value,'light');off();});
await check('UndoManager retains snapshots, supports redo and rolls back exceptions',()=>{let value={count:1};const u=new UndoManager(()=>value,v=>value=v);u.transaction(()=>value.count=2);assert(u.undo());assert.equal(value.count,1);assert(u.redo());assert.equal(value.count,2);assert.throws(()=>u.transaction(()=>{value.count=9;throw Error('rollback');}));assert.equal(value.count,2);});
await check('No-op transactions do not consume undo history',()=>{let x={a:1};const u=new UndoManager(()=>x,v=>x=v);u.transaction(()=>{});assert.equal(u.past.length,0);});
await check('Fluent view modifiers leave original descriptors unchanged',()=>{const a=Text('Hello'),b=a.padding(12).font('title').frame({maxWidth:Infinity});assert.equal(a.props.style,undefined);assert.equal(b.props.style.padding,'12px');assert.equal(b.props.style.maxWidth,'100%');assert.equal(VStack(a,b).children.length,2);});
await check('Validated declarative views compile bindings and named actions',()=>{const s=new State({text:'World'}),v={type:'Text',id:'hello',props:{text:'Hello {{text}}'}};K.validateView(v);assert.equal(K.fromJSON(v,{state:s}).props.text(),'Hello World');});
await check('View documents reject duplicate IDs and unknown components',()=>{assert.throws(()=>K.validateView({type:'VStack',id:'x',children:[{type:'Text',id:'x'}]}));assert.throws(()=>K.validateView({type:'script',id:'x'}));});
await check('Data validation rejects pollution keys and nonfinite values',()=>{assert.throws(()=>K.safeData(JSON.parse('{"__proto__":{"x":1}}')));assert.throws(()=>K.safeData({x:NaN}));assert.deepEqual(K.safeData({x:[1,true,'s']}),{x:[1,true,'s']});});
const report={passed:results.filter(r=>r.passed).length,failed:results.filter(r=>!r.passed).length,results};writeFileSync(new URL('./sdk-report.json',import.meta.url),JSON.stringify(report,null,2)+'\n');process.exitCode=report.failed?1:0;
