/* Three local games. Fixed-step physics and deterministic tile-combination rules. */
(function(D){
'use strict';const S=D.Studio,E=D.escape,G=S.Games={};
G.merge=(board,direction)=>{const next=board.slice();let score=0;const index=(line,i)=>direction==='left'?line*4+i:direction==='right'?line*4+3-i:direction==='up'?i*4+line:(3-i)*4+line;for(let l=0;l<4;l++){const values=Array.from({length:4},(_,i)=>board[index(l,i)]).filter(Boolean),out=[];for(let i=0;i<values.length;i++){if(values[i]===values[i+1]){out.push(values[i]*2);score+=values[i]*2;i++;}else out.push(values[i]);}while(out.length<4)out.push(0);for(let i=0;i<4;i++)next[index(l,i)]=out[i];}return {board:next,score,changed:next.some((v,i)=>v!==board[i])};};
G.available=board=>board.includes(0)||['left','right','up','down'].some(d=>G.merge(board,d).changed);
D.register({id:'arcade',name:'Arcade',rank:20,category:'Play',pattern:'Playfield + clubhouse',description:'Prism Break, Neon Serpent and Merge 2048: three complete local games.',boundary:'Original single-player browser games. No game-console emulation or online matchmaking.'},ctx=>{
 const m=()=>ctx.get({game:'breakout',best:{breakout:0,snake:0,merge:0},sound:true}),names={breakout:'Prism Break',snake:'Neon Serpent',merge:'Merge 2048'};let game,playing=false,raf=0,last=0,acc=0,keys=new Set(),audio=null,generation=0,disposed=false,touch=null;
 ctx.root.innerHTML=D.appHeader('arcade','Three worlds. One pocket.')+D.paneTabs('Playfield','Clubhouse')+`<div class="duo-panes pro-panes"><section class="pane primary-pane"><div class="arcade-bar"><div><small>DUO / ARCADE</small><h2></h2></div><strong class="arcade-score">0</strong>${S.button('game-start','▶ Play')}${S.button('game-reset','↻')}</div><div class="arcade-viewport pro-viewport"></div><div class="game-pad" role="group" aria-label="Game directional controls">${['left','up','down','right'].map((v,i)=>`<button data-direction="${v}" aria-label="${v}">${['←','↑','↓','→'][i]}</button>`).join('')}</div><div class="pro-status arcade-status"></div></section><aside class="pane secondary-pane pro-inspector"></aside></div>`;
 const q=s=>ctx.root.querySelector(s);const surface=S.surface(q('.arcade-viewport'),ctx.scope,draw,{label:'Arcade game field. Arrow keys move, Space plays or pauses.'});
 function tone(hz){if(!m().sound||!audio||audio.state!=='running')return;const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=hz;g.gain.setValueAtTime(.04*(D.store.data.prefs.volume??1),audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.12);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.13);o.onended=()=>{o.disconnect();g.disconnect();};}
 function best(){m().best[m().game]=Math.max(m().best[m().game]||0,game.score);ctx.save();q('.arcade-score').textContent=game.score;}
 const bricks=()=>Array.from({length:50},(_,i)=>({x:28+(i%10)*55,y:60+Math.floor(i/10)*25,w:49,h:17,alive:true,row:Math.floor(i/10)}));
 function spawn(){const free=game.board.map((v,i)=>v?null:i).filter(v=>v!==null);if(free.length)game.board[free[Math.floor(Math.random()*free.length)]]=Math.random()<.9?2:4;}
 function food(){const free=Array.from({length:400},(_,i)=>i).filter(i=>!game.body.includes(i));game.food=free[Math.floor(Math.random()*free.length)];if(!free.length)end('Perfect grid. You win!');}
 function reset(){stop();game=m().game==='breakout'?{score:0,level:1,lives:3,paddle:300,target:300,ball:{x:300,y:390,vx:165,vy:-250},bricks:bricks(),particles:[],over:false}:m().game==='snake'?{score:0,body:[210,209,208,207],direction:1,queued:1,food:45,tick:0,over:false}:{score:0,board:Array(16).fill(0),moves:0,over:false};if(m().game==='snake')food();if(m().game==='merge'){spawn();spawn();}render();}
 function render(){q('.arcade-bar h2').textContent=names[m().game];q('.arcade-score').textContent=game?.score||0;q('[data-action="game-start"]').textContent=playing?'Ⅱ Pause':'▶ Play';q('.pro-inspector').innerHTML=S.section('The clubhouse',`<div class="game-cards">${Object.entries(names).map(([id,name],i)=>`<button class="game-card ${id===m().game?'is-active':''}" data-game="${id}"><span>${['◈','⌁','2048'][i]}</span><div><b>${name}</b><small>Personal best ${m().best[id]||0}</small></div></button>`).join('')}</div>`)+S.section('How to play',S.help(m().game==='breakout'?'Move the paddle with the pointer, touch or arrow keys. Clear every prism. Three lives; successive levels get faster.':m().game==='snake'?'Arrow keys, swipe or the direction pad. Eat the light, grow your serpent, avoid the walls and your tail.': 'Swipe or use arrows to combine matching tiles. A tile merges once per move. Keep going beyond 2048.'))+S.toolbar(S.button('game-sound',m().sound?'Sound on':'Sound off'))+S.help('Games pause when hidden, locked or switched away. Personal bests stay in the local session.');surface.invalidate();}
 function stop(){generation++;playing=false;cancelAnimationFrame(raf);raf=0;keys.clear();audio?.suspend().catch(()=>{});if(q('[data-action="game-start"]'))q('[data-action="game-start"]').textContent='▶ Play';surface.invalidate();}
 async function play(){if(playing){stop();return;}if(game.over)reset();const ticket=++generation;try{if(m().sound){audio??=new (window.AudioContext||window.webkitAudioContext)();await audio.resume();}}catch{}if(ticket!==generation||disposed){audio?.suspend().catch(()=>{});return;}playing=true;last=performance.now();acc=0;render();raf=requestAnimationFrame(loop);surface.canvas.focus({preventScroll:true});}
 function end(message){game.over=true;game.message=message;best();stop();render();tone(180);}
 function input(dir){if(!playing)return;if(m().game==='merge'){const next=G.merge(game.board,dir);if(next.changed){game.board=next.board;game.score+=next.score;game.moves++;spawn();best();tone(240+Math.min(1000,next.score*3));if(!G.available(game.board))end('No moves remain. A beautiful run.');surface.invalidate();}}else if(m().game==='snake'){const d={left:-1,right:1,up:-20,down:20}[dir];if(d!==-game.direction)game.queued=d;}else game.target=Math.max(52,Math.min(548,game.target+(dir==='left'?-55:dir==='right'?55:0)));}
 function update(dt){if(m().game==='breakout'){const b=game.ball,oldY=b.y;game.target=Math.max(52,Math.min(548,game.target+((keys.has('right')?1:0)-(keys.has('left')?1:0))*450*dt));game.paddle+=(game.target-game.paddle)*Math.min(1,22*dt);b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<9){b.x=9;b.vx=Math.abs(b.vx);tone(250);}if(b.x>591){b.x=591;b.vx=-Math.abs(b.vx);tone(250);}if(b.y<9){b.y=9;b.vy=Math.abs(b.vy);}if(b.vy>0&&oldY+8<442&&b.y+8>=442&&Math.abs(b.x-game.paddle)<62){const a=(b.x-game.paddle)/62*1.1,speed=Math.min(520,310+22*game.level);b.vx=Math.sin(a)*speed;b.vy=-Math.cos(a)*speed;b.y=433;tone(390);}for(const brick of game.bricks){if(!brick.alive||b.x+8<brick.x||b.x-8>brick.x+brick.w||b.y+8<brick.y||b.y-8>brick.y+brick.h)continue;brick.alive=false;game.score+=10;if(oldY+8<=brick.y||oldY-8>=brick.y+brick.h)b.vy=-b.vy;else b.vx=-b.vx;for(let i=0;i<8;i++)game.particles.push({x:b.x,y:b.y,vx:(Math.random()-.5)*160,vy:(Math.random()-.5)*160,life:.55});best();tone(420+brick.row*90);break;}game.particles=game.particles.filter(p=>(p.life-=dt)>0);for(const p of game.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;}if(b.y>510){if(--game.lives<=0)end('Every prism is another possibility.');else Object.assign(b,{x:300,y:390,vx:165,vy:-250});}if(game.bricks.every(b=>!b.alive)){game.level++;game.bricks=bricks();Object.assign(b,{x:300,y:390,vx:180,vy:-280});}}else if(m().game==='snake'){game.tick+=dt;const interval=1/Math.min(16,8+game.score/50);if(game.tick<interval)return;game.tick-=interval;game.direction=game.queued;const head=game.body[0],next=head+game.direction,grows=next===game.food;if(next<0||next>=400||(game.direction===1&&head%20===19)||(game.direction===-1&&head%20===0)||game.body.slice(0,grows?undefined:-1).includes(next)){end('The serpent rests. Try a new path.');return;}game.body.unshift(next);if(grows){game.score+=10;best();tone(540);food();}else game.body.pop();}}
 function loop(now){if(!playing||disposed)return;acc+=Math.min(.05,(now-last)/1000);last=now;let count=0;while(acc>=1/120&&count++<8&&playing){update(1/120);acc-=1/120;}surface.invalidate();if(playing)raf=requestAnimationFrame(loop);}
 function draw(g,w,h){g.fillStyle='#0c1120';g.fillRect(0,0,w,h);if(!game)return;const scale=Math.min(w/600,h/490),ox=(w-600*scale)/2,oy=(h-490*scale)/2;g.save();g.translate(ox,oy);g.scale(scale,scale);g.fillStyle='#10172a';g.fillRect(0,0,600,490);if(m().game==='breakout'){for(const b of game.bricks)if(b.alive){g.fillStyle=['#cb89ff','#a09dfc','#77c5ea','#72d6c1','#f0c58b'][b.row];g.beginPath();g.roundRect(b.x,b.y,b.w,b.h,5);g.fill();}g.fillStyle='#ececff';g.beginPath();g.roundRect(game.paddle-52,442,104,10,5);g.fill();g.shadowColor='#b3aeff';g.shadowBlur=18;g.beginPath();g.arc(game.ball.x,game.ball.y,8,0,Math.PI*2);g.fill();g.shadowBlur=0;for(const p of game.particles){g.globalAlpha=p.life/.55;g.fillRect(p.x,p.y,3,3);}g.globalAlpha=1;}else if(m().game==='snake'){const x0=90,y0=35,s=21;g.strokeStyle='#ffffff08';for(let x=0;x<=20;x++){g.beginPath();g.moveTo(x0+x*s,y0);g.lineTo(x0+x*s,y0+420);g.moveTo(x0,y0+x*s);g.lineTo(x0+420,y0+x*s);g.stroke();}game.body.forEach((b,i)=>{g.fillStyle=i?'#5bcdb4':'#cefde5';g.beginPath();g.roundRect(x0+b%20*s+2,y0+Math.floor(b/20)*s+2,17,17,4);g.fill();});g.fillStyle='#f995c5';g.beginPath();g.arc(x0+game.food%20*s+10,y0+Math.floor(game.food/20)*s+10,7,0,Math.PI*2);g.fill();}else{for(let i=0;i<16;i++){const v=game.board[i],x=98+i%4*103,y=38+Math.floor(i/4)*103;g.fillStyle=v?`hsl(${255-Math.log2(v)*12} 55% ${28+Math.log2(v)*3}%)`:'#ffffff08';g.beginPath();g.roundRect(x,y,94,94,15);g.fill();if(v){g.fillStyle='white';g.font='700 '+(v>999?25:33)+'px system-ui';g.textAlign='center';g.fillText(v,x+47,y+58);}}}if(!playing){g.fillStyle='#0b1029b0';g.fillRect(0,0,600,490);g.textAlign='center';g.fillStyle='#fff';g.font='700 28px system-ui';g.fillText(game.over?'A good run.':names[m().game],300,227);g.font='14px system-ui';g.fillStyle='#c5c8dd';g.fillText(game.over?'Press Play to start again.':'Press Play or Space. Make a little time for play.',300,258);}g.restore();q('.arcade-status').textContent=m().game==='breakout'?`Level ${game.level} · ${game.lives} lives · best ${m().best.breakout}`:m().game==='snake'?`${game.body.length} segments · best ${m().best.snake}`:`${game.moves} moves · best ${m().best.merge}`;}
 const direction={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'};ctx.scope.on(surface.canvas,'keydown',e=>{if(e.code==='Space'){e.preventDefault();if(!e.repeat)play();}if(direction[e.key]){e.preventDefault();keys.add(direction[e.key]);if(!e.repeat||m().game!=='snake')input(direction[e.key]);}});ctx.scope.on(window,'keyup',e=>keys.delete(direction[e.key]));ctx.scope.on(window,'blur',()=>keys.clear());
 const logical=e=>{const p=surface.point(e),scale=Math.min(surface.width/600,surface.height/490);return {x:(p.x-(surface.width-600*scale)/2)/scale,y:(p.y-(surface.height-490*scale)/2)/scale};};ctx.scope.on(surface.canvas,'pointerdown',e=>{surface.canvas.focus();touch={x:e.clientX,y:e.clientY};if(m().game==='breakout')game.target=logical(e).x;try{surface.canvas.setPointerCapture(e.pointerId);}catch{}e.preventDefault();});ctx.scope.on(surface.canvas,'pointermove',e=>{if(m().game==='breakout')game.target=Math.max(52,Math.min(548,logical(e).x));});ctx.scope.on(surface.canvas,'pointerup',e=>{if(touch){const x=e.clientX-touch.x,y=e.clientY-touch.y;if(Math.max(Math.abs(x),Math.abs(y))>23)input(Math.abs(x)>Math.abs(y)?x>0?'right':'left':y>0?'down':'up');touch=null;}});ctx.scope.on(surface.canvas,'pointercancel',()=>touch=null);
 ctx.scope.on(ctx.root,'click',e=>{const b=e.target.closest('[data-game]');if(b)setGame(b.dataset.game);const pad=e.target.closest('[data-direction]');if(pad)input(pad.dataset.direction);});function setGame(id){if(!names[id])throw Error('Unknown game');m().game=id;ctx.save();reset();}
 ctx.act('game-start',play);ctx.act('game-reset',reset);ctx.act('game-sound',()=>{m().sound=!m().sound;ctx.save();render();});ctx.listen('restore',id=>{if(id===ctx.id)reset();});reset();return {render,play,stop,input,reset,setGame,get game(){return game;},get playing(){return playing;},resume:()=>surface.invalidate(),suspend:stop,dispose(){disposed=true;stop();audio?.close().catch(()=>{});}};
});
})(window.Duo);
