(function(D){'use strict';const S=D.Studio,G=S.Geometry;
const vase=()=>[[0,-1.2],[.75,-1.2],[.75,-.95],[.48,-.75],[.55,-.25],[.95,.3],[.85,.7],[.38,1],[.38,1.2],[.23,1.2],[.23,1],[.67,.7],[.75,.3],[.36,-.2],[.3,-.8],[0,-.8]],star=()=>Array.from({length:10},(_,i)=>{const a=i*Math.PI/5-Math.PI/2,r=i%2?.5:1.2;return[Math.cos(a)*r,Math.sin(a)*r];});
D.register({id:'polyform',name:'Polyform',rank:13,category:'Create',pattern:'Mesh + construction profile',description:'Shape revolved or twisted extruded meshes by editing a 2D construction profile, with live 3D feedback and STL/OBJ output.',boundary:'Profile-based polygon modeling with concave triangulation. No NURBS, sculpt brushes, topology booleans or manufacturing certification.'},ctx=>{
const doc=S.document(ctx,{title:'A vessel for tomorrow',profile:vase(),method:'lathe',depth:1.5,segments:48,twist:0,camera:{yaw:.8,pitch:.24,distance:6.5,target:[0,0,0]},wire:false}),m=doc.state;let mounted=false,view,profileSurface,mesh,selection=3,drag=-1;
function construct(){return m().method==='lathe'?G.lathe(m().profile,m().segments):G.extrude(m().profile,m().depth,m().twist,Math.max(1,Math.round(m().segments/3)));}
function updateMesh(){try{mesh=construct();view.setObjects([{id:'form',name:m().title,type:'mesh',mesh,color:'#edab88',position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]}],'',m().wire);D.$('.poly-status',ctx.root).textContent=`${mesh.vertices.length} vertices · ${mesh.faces.length} triangles · ${m().profile.length} profile points`;}catch(e){D.$('.poly-status',ctx.root).textContent=e.message;}profileSurface?.invalidate();}
function render(){if(!mounted){ctx.root.innerHTML=doc.header('Procedural form studio',S.button('poly-wire','Wireframe'))+D.paneTabs('Form','Construction')+`<div class="duo-panes pro-panes"><div class="pane primary-pane"><div class="pro-viewport poly-viewport"></div><div class="pro-status poly-status"></div></div><div class="pane secondary-pane pro-inspector"><div class="poly-controls"></div><div class="profile-editor"></div><div class="poly-point"></div><div class="poly-actions"></div></div></div>`;view=new S.View3D(D.$('.poly-viewport',ctx.root),ctx.scope,{camera:m().camera,onCamera:()=>ctx.save()});profileSurface=S.surface(D.$('.profile-editor',ctx.root),ctx.scope,drawProfile,{label:'Editable 2D construction profile. Drag control points.'});bindProfile();mounted=true;}D.$('.poly-controls',ctx.root).innerHTML=S.section('CONSTRUCTION',S.field('title','Name',m().title,'text')+S.select('method','Generator',m().method,[['lathe','Revolve profile'],['extrude','Twisted extrusion']])+`<div class="pro-fields">${S.field('segments','Segments',m().segments,'number','min="3" max="128" step="1"')}${S.field('depth','Depth',m().depth,'number','min="0.1" max="8" step="0.1"')}${S.field('twist','Twist °',m().twist,'number','min="-360" max="360" step="5"')}</div>`);pointControls();D.$('.poly-actions',ctx.root).innerHTML=S.section('CONSTRUCTION TOOLS',`<div class="pro-row">${S.button('subdivide','Subdivide')}${S.button('add-point','Add point')}${S.button('remove-point','Remove')}</div><div class="pro-row">${S.button('vase','Vessel preset')}${S.button('star','Star preset')}</div>`)+S.section('FABRICATE / SHARE',`<div class="pro-row">${S.button('stl','STL ↓')}${S.button('obj','OBJ ↓')}${S.button('send-scene','Send to SceneLab')}</div>`)+S.help('Drag profile points for live geometry. Revolve uses X as radius and Y as height. Extrusion requires a simple closed profile. Inspect meshes before fabrication.');view.updateCamera(m().camera);updateMesh();ctx.pane(ctx.root.dataset.activePane||'primary');}
function pointControls(){selection=Math.min(selection,m().profile.length-1);const p=m().profile[selection]||[0,0];D.$('.poly-point',ctx.root).innerHTML=`<div class="pro-section"><h3>POINT ${selection+1} / ${m().profile.length}</h3><div class="pro-fields">${S.field('point-x','X / radius',p[0].toFixed(3),'number','step="0.05"')}${S.field('point-y','Y / height',p[1].toFixed(3),'number','step="0.05"')}</div><div class="pro-row">${S.button('previous-point','← Previous')}${S.button('next-point','Next →')}</div></div>`;}
function project(p,w=profileSurface.width,h=profileSurface.height){const scale=Math.min(w,h)/4.5;return{x:w/2+p[0]*scale,y:h/2-p[1]*scale};}function unproject(p){const scale=Math.min(profileSurface.width,profileSurface.height)/4.5;return[S.finite((p.x-profileSurface.width/2)/scale,0,m().method==='lathe'?0:-2,2),S.finite((profileSurface.height/2-p.y)/scale,0,-2,2)];}
function drawProfile(g,w,h){g.fillStyle='#0b1524';g.fillRect(0,0,w,h);for(let n=-2;n<=2;n+=.5){const a=project([n,-2],w,h),b=project([n,2],w,h),c=project([-2,n],w,h),d=project([2,n],w,h);g.strokeStyle=n===0?'#4f6682':'#223147';g.lineWidth=.7;g.beginPath();g.moveTo(a.x,a.y);g.lineTo(b.x,b.y);g.moveTo(c.x,c.y);g.lineTo(d.x,d.y);g.stroke();}g.beginPath();m().profile.forEach((p,i)=>{const q=project(p,w,h);i?g.lineTo(q.x,q.y):g.moveTo(q.x,q.y);});g.closePath();g.fillStyle='#d69d7433';g.fill();g.strokeStyle='#ffbc8e';g.lineWidth=1.8;g.stroke();m().profile.forEach((p,i)=>{const q=project(p,w,h);g.fillStyle=i===selection?'#fff3d6':'#e3a079';g.beginPath();g.arc(q.x,q.y,i===selection?5:3.3,0,Math.PI*2);g.fill();});}
function bindProfile(){const canvas=profileSurface.canvas;ctx.scope.on(canvas,'pointerdown',e=>{const p=profileSurface.point(e);let distance=15;drag=-1;m().profile.forEach((q,i)=>{const at=project(q),d=Math.hypot(p.x-at.x,p.y-at.y);if(d<distance){distance=d;drag=i;}});if(drag<0)return;e.preventDefault();try{canvas.setPointerCapture(e.pointerId);}catch{}selection=drag;D.store.checkpoint(ctx.id);pointControls();profileSurface.invalidate();});ctx.scope.on(canvas,'pointermove',e=>{if(drag<0)return;m().profile[drag]=unproject(profileSurface.point(e));pointControls();updateMesh();});for(const type of['pointerup','pointercancel','lostpointercapture'])ctx.scope.on(canvas,type,()=>{drag=-1;ctx.save();});}
ctx.scope.on(ctx.root,'change',e=>{const key=e.target.dataset.field;if(!key)return;doc.change(s=>{if(key==='title')s.title=e.target.value.slice(0,100);else if(key==='method'){s.method=e.target.value;s.profile=s.method==='lathe'?vase():star();selection=0;}else if(key.startsWith('point-'))s.profile[selection][key==='point-x'?0:1]=S.finite(e.target.value,0,key==='point-x'&&s.method==='lathe'?0:-2,2);else if(key==='segments')s.segments=Math.round(S.finite(e.target.value,48,3,128));else if(key==='depth')s.depth=S.finite(e.target.value,1,.1,8);else if(key==='twist')s.twist=S.finite(e.target.value,0,-360,360);});render();});
ctx.act('previous-point',()=>{selection=(selection+m().profile.length-1)%m().profile.length;pointControls();profileSurface.invalidate();});ctx.act('next-point',()=>{selection=(selection+1)%m().profile.length;pointControls();profileSurface.invalidate();});ctx.act('poly-wire',()=>{m().wire=!m().wire;ctx.save();updateMesh();});ctx.act('subdivide',()=>{if(m().profile.length>64)return D.toast('Maximum 128 profile points.');doc.change(s=>s.profile=s.profile.flatMap((p,i)=>{const q=s.profile[(i+1)%s.profile.length];return[p,[(p[0]+q[0])/2,(p[1]+q[1])/2]];}));render();});ctx.act('add-point',()=>{if(m().profile.length>=128)return;doc.change(s=>{const a=s.profile[selection],b=s.profile[(selection+1)%s.profile.length];s.profile.splice(++selection,0,[(a[0]+b[0])/2,(a[1]+b[1])/2]);});render();});ctx.act('remove-point',()=>{if(m().profile.length<=3)return;doc.change(s=>s.profile.splice(selection,1));render();});for(const preset of['vase','star'])ctx.act(preset,()=>{doc.change(s=>{s.method=preset==='vase'?'lathe':'extrude';s.profile=preset==='vase'?vase():star();selection=0;});render();});
const obj=()=>[{id:'form',name:m().title,type:'mesh',mesh:construct(),position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]}];ctx.act('stl',()=>D.download(m().title+'.stl',G.stl(obj()),'model/stl'));ctx.act('obj',()=>D.download(m().title+'.obj',G.obj(obj()),'text/plain'));ctx.act('send-scene',()=>D.emit('transfer',{app:'scenelab',artifact:{type:'mesh',mesh:construct(),title:m().title,source:'polyform'}}));
render();return{render,construct,get renderer(){return view;},receive(a){doc.load(S.parseJSON(a.text));},resume(){view.invalidate();profileSurface.invalidate();}};
});})(window.Duo);
