(function(D){'use strict';const S=D.Studio,A=S.Audio;
D.register({id:'pulse',name:'Pulse',rank:14,category:'Create',pattern:'Sequencer + mixer',description:'A playable drum machine and polyphonic synth with a 16/32-step sequencer, swing, mixing, piano audition, WAV bounce and MIDI export.',boundary:'Built-in synthesized instruments. No external plug-ins, VST/AU hosting, streaming music service or multitrack microphone recorder.'},ctx=>{
const track=(id,name,kind,pitch,hits,gain=.7)=>({id,name,kind,pitch,gain,pan:0,cutoff:9000,mute:false,solo:false,pattern:Array.from({length:16},(_,i)=>hits.includes(i)?(i%4?.65:1):0)});
const doc=S.document(ctx,{title:'Midnight at the atelier',bpm:108,swing:.15,steps:16,bars:4,selected:'bass',tracks:[track('kick','Warm kick','kick',36,[0,4,8,12]),track('snare','Soft snare','snare',38,[4,12],.55),track('hat','Silk hats','hat',42,[0,2,4,6,8,10,12,14],.5),track('bass','Velvet bass','bass',36,[0,3,6,8,11,14],.65),track('chord','Daydream','chord',60,[0,6,10],.55),track('lead','Afterglow','lead',72,[3,7,11,15],.22)]}),m=doc.state;
let mounted=false,wave,frame=0,current=-1,active=true,bouncing=false;const engine=new A.Sequencer(m,step=>{current=step;D.$$('[data-step]',ctx.root).forEach(b=>b.classList.toggle('playhead',step>=0&&+b.dataset.step===step));const label=D.$('.pulse-time',ctx.root);if(label)label.textContent=step<0?'STOPPED':`STEP ${String(step+1).padStart(2,'0')} / ${m().steps}`;});const selected=()=>m().tracks.find(t=>t.id===m().selected)||m().tracks[0];
function render(){if(!mounted){ctx.root.innerHTML=doc.header('Synthesis · rhythm · arrangement',S.button('bounce','Bounce WAV'))+D.paneTabs('Sequencer','Mixer')+`<div class="duo-panes pro-panes"><div class="pane primary-pane pulse-main"><div class="pulse-transport"></div><div class="pulse-wave"></div><div class="pulse-grid-host scroll"></div><div class="piano-keyboard" role="group" aria-label="Synth keyboard"></div><div class="pro-status">Audio-clock scheduling · original synthesis · local WAV and MIDI</div></div><div class="pane secondary-pane pro-inspector"></div></div>`;wave=S.surface(D.$('.pulse-wave',ctx.root),ctx.scope,drawWave,{label:'Audio waveform'});mounted=true;}D.$('.pulse-transport',ctx.root).innerHTML=`${S.button('play',engine.running?'Ⅱ Pause':'▶ Play',engine.running)}${S.button('stop','■ Stop')}<span class="pulse-tempo">${m().bpm}<small>BPM</small></span><span class="pro-spacer"></span><span class="pulse-time">${engine.running?'PLAYING':'STOPPED'}</span>`;
D.$('.pulse-grid-host',ctx.root).innerHTML=`<div class="step-grid" style="--steps:${m().steps}"><div class="step-header">TRACK / MIX</div>${Array.from({length:m().steps},(_,i)=>`<div class="step-number">${i+1}</div>`).join('')}${m().tracks.map((t,index)=>`<button class="track-label ${t.id===selected().id?'selected':''}" data-action="select-track" data-track="${t.id}"><i style="background:${['#ffb49c','#df99ca','#a7a7f2','#89dad2','#e8d093','#95bef4'][index%6]}"></i><span>${D.escape(t.name)}<small>${t.mute?'MUTED':t.solo?'SOLO':t.kind}</small></span></button>${t.pattern.map((v,i)=>`<button data-action="step" data-track="${t.id}" data-step="${i}" class="step-pad ${v?'on':''} ${v===1?'accent':''} ${i%4===0?'bar-start':''} ${current===i?'playhead':''}" aria-label="${D.escape(t.name)} step ${i+1}" aria-pressed="${!!v}"><i></i></button>`).join('')}`).join('')}</div>`;
D.$('.piano-keyboard',ctx.root).innerHTML=Array.from({length:13},(_,i)=>`<button data-action="note" data-note="${48+i}" class="piano-key ${[1,3,6,8,10].includes(i%12)?'black':''}" aria-label="Play MIDI note ${48+i}">${['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'][i%12]}${i===0?'3':i===12?'4':''}</button>`).join('');inspector();wave.invalidate();ctx.pane(ctx.root.dataset.activePane||'primary');}
function inspector(){const t=selected();D.$('.pro-inspector',ctx.root).innerHTML=S.section('ARRANGEMENT',S.field('title','Project',m().title,'text')+`<div class="pro-fields">${S.field('bpm','Tempo',m().bpm,'number','min="30" max="240"')}${S.field('bars','Export loops',m().bars,'number','min="1" max="16"')}</div>`+S.field('swing','Swing',m().swing,'range','min="0" max="0.9" step="0.01"')+S.select('steps','Pattern length',String(m().steps),[['16','16 steps'],['32','32 steps']]))+S.section('SELECTED TRACK',S.field('name','Name',t.name,'text')+S.select('kind','Instrument',t.kind,['kick','snare','hat','bass','chord','lead'])+`<div class="pro-row">${S.button('mute','Mute',t.mute)}${S.button('solo','Solo',t.solo)}${S.button('audition','Audition')}</div>`+S.field('gain','Level',t.gain,'range','min="0" max="1" step="0.01"')+S.field('pan','Stereo pan',t.pan,'range','min="-1" max="1" step="0.01"')+S.field('cutoff','Low-pass Hz',t.cutoff,'range','min="80" max="16000" step="20"')+S.field('pitch','MIDI note',t.pitch,'number','min="24" max="96"'))+S.section('PATTERN TOOLS',`<div class="pro-row">${S.button('rotate-pattern','Rotate →')}${S.button('clear-track','Clear')}${S.button('add-track','Add track')}</div><div class="pro-row">${S.button('midi','Export MIDI')}${S.button('bounce','Bounce WAV')}</div>`)+S.help('Click a step to toggle. Shift-click cycles soft / accent / off. Each track has level, stereo pan, filter and pitch. The keyboard auditions the selected instrument.');}
function drawWave(g,w,h){g.fillStyle='#121020';g.fillRect(0,0,w,h);g.strokeStyle='#c291e5';g.lineWidth=1.6;g.beginPath();const data=new Uint8Array(256);if(engine.analyser&&engine.running)engine.analyser.getByteTimeDomainData(data);else data.fill(128);for(let i=0;i<data.length;i++){const x=i/(data.length-1)*w,y=h/2+(data[i]-128)/128*h*.43;i?g.lineTo(x,y):g.moveTo(x,y);}g.stroke();g.fillStyle='#a19bb9';g.font='9px ui-monospace,monospace';g.fillText('PULSE / STEREO MASTER',12,15);}
function animate(){cancelAnimationFrame(frame);if(!engine.running||!active||document.hidden)return;wave.invalidate();frame=requestAnimationFrame(animate);}async function play(){if(engine.running){engine.stop();cancelAnimationFrame(frame);}else{await engine.play();animate();}render();}
async function bounce(){if(bouncing)return;const snapshot=S.clone(m());bouncing=true;D.toast('Rendering '+snapshot.bars+' loops to stereo PCM');try{const buffer=await A.render(snapshot),bytes=A.wav(buffer);await S.files.put({name:snapshot.title+'.wav',type:'audio/wav',app:'audio',data:bytes});D.download(snapshot.title+'.wav',bytes,'audio/wav');D.notify?.({app:'pulse',title:'Bounce complete',text:buffer.duration.toFixed(1)+' seconds · stereo WAV'});return bytes;}finally{bouncing=false;}}
ctx.act('play',play);ctx.act('stop',()=>{engine.stop();cancelAnimationFrame(frame);render();});ctx.act('bounce',bounce);ctx.act('midi',()=>D.download(m().title+'.mid',A.midi(m()),'audio/midi'));ctx.act('note',b=>engine.preview(selected(),+b.dataset.note));ctx.act('audition',()=>engine.preview(selected(),selected().pitch));ctx.act('select-track',b=>{m().selected=b.dataset.track;ctx.save();render();});
ctx.act('step',(b,e)=>{const track=m().tracks.find(t=>t.id===b.dataset.track),i=+b.dataset.step;doc.change(()=>{track.pattern[i]=e.shiftKey?(track.pattern[i]===0?.5:track.pattern[i]===.5?1:0):(track.pattern[i]?0:.8);},false);b.classList.toggle('on',!!track.pattern[i]);b.classList.toggle('accent',track.pattern[i]===1);b.setAttribute('aria-pressed',!!track.pattern[i]);});
for(const key of['mute','solo'])ctx.act(key,()=>{doc.change(()=>selected()[key]=!selected()[key]);render();});ctx.act('rotate-pattern',()=>{doc.change(()=>{const t=selected();t.pattern.unshift(t.pattern.pop());});render();});ctx.act('clear-track',()=>{doc.change(()=>selected().pattern.fill(0));render();});ctx.act('add-track',()=>{if(m().tracks.length>=16)return;doc.change(s=>{const t=track(D.uid(),'New instrument','lead',60,[],.4);t.pattern=Array(s.steps).fill(0);s.tracks.push(t);s.selected=t.id;});render();});
ctx.scope.on(ctx.root,'change',async e=>{const key=e.target.dataset.field;if(!key)return;const wasRunning=engine.running;if(['bpm','steps','swing'].includes(key))engine.stop();doc.change(s=>{if(key==='title')s.title=e.target.value.slice(0,100);else if(key==='steps'){s.steps=Number(e.target.value);s.tracks.forEach(t=>t.pattern=Array.from({length:s.steps},(_,i)=>t.pattern[i]||0));}else if(key==='bpm')s.bpm=S.finite(e.target.value,108,30,240);else if(key==='bars')s.bars=Math.round(S.finite(e.target.value,4,1,16));else if(key==='swing')s.swing=S.finite(e.target.value,0,0,.9);else{const t=selected();if(key==='kind')t.kind=e.target.value;else if(key==='name')t.name=e.target.value.slice(0,80);else t[key]=S.finite(e.target.value,t[key],key==='pitch'?24:key==='cutoff'?80:key==='pan'?-1:0,key==='pitch'?96:key==='cutoff'?16000:1);}});if(wasRunning&&!engine.running){await engine.play();animate();}render();});ctx.scope.on(document,'visibilitychange',()=>{if(document.hidden){engine.stop();cancelAnimationFrame(frame);render();}});
render();return{render,engine,bounce,receive(a){engine.stop();doc.load(S.parseJSON(a.text));},suspend(){active=false;engine.stop();cancelAnimationFrame(frame);},resume(){active=true;render();},dispose(){cancelAnimationFrame(frame);engine.dispose();}};
});})(window.Duo);
