(function (D) {
    'use strict';
    const initial = () => [
        { id: 't1', name: 'Sofia Chen', handle: 'sofia.studies', time: '12m', text: 'Maybe the most useful thing about more screen is not doing more. It is having room to stay with one idea a little longer.', art: 'dunes', likes: 128, liked: false, saved: false, followed: true, reposted: false, replies: [{ name: 'Noah Rivers', text: 'Exactly this. Space for the work, not just more windows.' }, { name: 'Maya Torres', text: 'A reference beside a sketch. That is all I need.' }] },
        { id: 't2', name: 'Leo Park', handle: 'leo.forms', time: '38m', text: 'A good interface should feel like opening a window, not opening a manual.\n\nWhat is one tiny interaction that made your day better?', likes: 84, liked: false, saved: false, followed: true, reposted: false, replies: [{ name: 'Ari Lane', text: 'When the thing I was reading stays where I left it.' }] },
        { id: 't3', name: 'Maya Torres', handle: 'maya.outside', time: '1h', text: 'Today’s color palette: blue hour, quiet mountains, and absolutely no notifications.', art: 'alpine', likes: 246, liked: false, saved: false, followed: false, reposted: false, replies: [{ name: 'Sofia Chen', text: 'This is the mood for the entire weekend.' }] },
        { id: 't4', name: 'Ari Lane', handle: 'ari.objects', time: '2h', text: 'Made a little object that feels like it belongs somewhere between a studio and a dream.', art: 'orbital', likes: 73, liked: false, saved: false, followed: false, reposted: false, replies: [] },
        { id: 't5', name: 'Noah Rivers', handle: 'noah.rivers', time: '3h', text: 'A Sunday plan: coffee, one long walk, and nowhere to be afterwards. Simple does not have to mean ordinary.', likes: 59, liked: false, saved: false, followed: true, reposted: false, replies: [{ name: 'Leo Park', text: 'The coffee part is essential.' }] },
    ];
    D.SDK.register({ id: 'threads', name: 'Threads', rank: 2, pattern: 'Feed + conversation', description: 'Follow the stream without losing the thread. Open a conversation beside your feed, then reply, save, or publish locally.', tip: 'Open a thread, write a reply, then try the Following and Saved filters. Your place in the feed is independent of the conversation.', boundary: 'Posts, profiles, follows, likes, and replies are local demonstration data. There is no Meta connection or public publishing.' }, D.SDK.UIViewRepresentable(ctx => {
        const { root, scope } = ctx;
        const m = () => ctx.get({ posts: initial(), selected: 't1', filter: 'all', reply: '', search: '' });
        const selected = () => m().posts.find(p => p.id === m().selected) || m().posts[0];
        function controls(p) { return `<div class="social-actions"><button data-action="like" data-id="${p.id}" class="${p.liked ? 'liked' : ''}" aria-label="${p.liked ? 'Unlike' : 'Like'} post">${D.icon('heart')} ${p.likes + (p.liked ? 1 : 0)}</button><button data-action="open-post" data-id="${p.id}" aria-label="Open conversation">${D.icon('comment')} ${p.replies.length}</button><button data-action="repost" data-id="${p.id}" class="${p.reposted ? 'saved' : ''}" aria-label="Repost locally">${D.icon('refresh')} ${p.reposted ? '1' : ''}</button><button data-action="share-post" data-id="${p.id}" aria-label="Share post">${D.icon('send')}</button><span class="spacer"></span><button data-action="save" data-id="${p.id}" class="${p.saved ? 'saved' : ''}" aria-label="${p.saved ? 'Unsave' : 'Save'} post">${D.icon('bookmark')}</button></div>`; }
        function postTop(p) { return `<div class="post-top">${D.avatar(p.name)}<div class="grow"><strong>${D.escape(p.name)}</strong><div><small>@${D.escape(p.handle)} · ${D.escape(p.time)}</small></div></div>${D.ib('open-post', 'more', 'Open this conversation', `data-id="${p.id}"`)}</div>`; }
        function render() { const s = m(), p = selected(); const posts = s.posts.filter(p => (s.filter !== 'following' || p.followed) && (s.filter !== 'saved' || p.saved) && (!s.search || (p.text + ' ' + p.name).toLowerCase().includes(s.search.toLowerCase()))); root.innerHTML = D.appHeader('threads', 'Local conversations', D.ib('search-posts', 'search', 'Search local posts')) + D.paneTabs('Your feed', 'Conversation') + `<div class="duo-panes"><div class="pane primary-pane"><div class="pane-toolbar"><h2 class="social-heading">For the curious.</h2>${D.ib('compose', 'edit', 'Write a new thread')}</div><div class="chip-row">${[['all', 'For you'], ['following', 'Following'], ['saved', 'Saved']].map(([id, label]) => `<button data-action="filter" data-filter="${id}" class="chip ${s.filter === id ? 'active' : ''}">${label}</button>`).join('')}${s.search ? `<button data-action="clear-search" class="chip">${D.escape(s.search)} ×</button>` : ''}</div><div class="thread-compose">${D.avatar('You', 'you')}<button data-action="compose">What is on your mind?</button>${D.icon('edit', 16)}</div><div class="scroll" id="thread-feed">${posts.length ? posts.map(p => `<article class="social-post">${postTop(p)}<button style="text-align:left;padding:0;width:100%" data-action="open-post" data-id="${p.id}"><p class="post-text">${D.escape(p.text)}</p></button>${p.art ? `<button class="post-art" style="padding:0;width:100%" data-action="open-post" data-id="${p.id}">${D.image(p.art, 'Original ' + p.art + ' digital study')}</button>` : ''}${controls(p)}</article>`).join('') : D.empty('bookmark', 'A little space for something good', 'No posts match this view yet. Save a thread or follow a creator to find it here.')}</div></div><div class="pane secondary-pane"><div class="pane-toolbar"><div><h3>Stay in the conversation</h3><small>The feed is still right there</small></div>${p ? D.btn('follow', null, p.followed ? 'Following' : 'Follow', 'small ghost') : ''}</div>${p ? `<div class="scroll"><article class="thread-detail">${postTop(p)}<p class="post-text">${D.escape(p.text)}</p>${p.art ? `<div class="post-art">${D.image(p.art, 'Original digital study')}</div>` : ''}${controls(p)}</article><div class="replies-heading">${p.replies.length} replies · local conversation</div>${p.replies.map(r => `<div class="reply">${D.avatar(r.name, 'tiny')}<div><b>${D.escape(r.name)}</b><p>${D.escape(r.text)}</p></div></div>`).join('')}</div><form class="composer" id="thread-reply"><div class="composer-box">${D.avatar('You', 'tiny you')}<input name="reply" placeholder="Add your perspective…" aria-label="Reply to thread" value="${D.escape(s.reply)}"><button class="send-btn" type="submit" aria-label="Post reply locally">${D.icon('arrow')}</button></div></form>` : D.empty('comment', 'Start a conversation', 'Write your first local thread.')}</div></div>`; ctx.pane(root.dataset.activePane || 'primary'); }
        function publish() { D.dialog('A thought worth sharing', `<div class="row" style="margin-bottom:15px">${D.avatar('You', 'you')}<div><b style="font-size:13px">You</b><p class="tiny muted">Local post · only visible in this browser</p></div></div><textarea id="new-thread" class="field" rows="5" maxlength="2000" aria-label="New thread text" placeholder="What is on your mind?"></textarea><label class="field-label" style="margin-top:14px">Add an original study<select id="new-thread-art" class="field"><option value="">Text only</option>${D.scenes.map(s => `<option value="${s.id}">${s.name}</option>`).join('')}</select></label><div class="dialog-footer"><span class="tiny muted">Not published to Threads</span><button class="btn primary" id="publish-thread">Post locally</button></div>`, body => { D.$('#publish-thread', body).onclick = () => { const text = D.$('#new-thread', body).value.trim(); if (!text) {
            D.$('#new-thread', body).focus();
            return;
        } D.store.checkpoint('threads'); const p = { id: D.uid(), name: 'You', handle: 'you', time: 'Just now', text, art: D.$('#new-thread-art', body).value, likes: 0, liked: false, saved: false, followed: true, reposted: false, replies: [] }; m().posts.unshift(p); m().selected = p.id; m().filter = 'all'; ctx.save(); D.$('#system-dialog').close(); render(); D.toast('Your thread was added locally'); }; }); }
        ctx.act('compose', publish);
        ctx.act('filter', b => { m().filter = b.dataset.filter; ctx.save(); render(); });
        ctx.act('open-post', b => { m().selected = b.dataset.id; ctx.save(); render(); ctx.pane('secondary'); });
        for (const [action, prop] of [['like', 'liked'], ['save', 'saved'], ['repost', 'reposted']])
            ctx.act(action, b => { const p = m().posts.find(p => p.id === b.dataset.id); if (!p)
                return; p[prop] = !p[prop]; ctx.save(); render(); });
        ctx.act('follow', () => { const p = selected(); p.followed = !p.followed; ctx.save(); render(); });
        ctx.act('share-post', b => { const p = m().posts.find(p => p.id === b.dataset.id); ctx.share(p.text, `A thought from ${p.name}`); });
        ctx.act('search-posts', () => D.dialog('Search the local conversation', `<input class="field" id="threads-search" placeholder="Search words or names" value="${D.escape(m().search)}" aria-label="Search local threads"><button class="btn primary" id="apply-thread-search" style="margin-top:15px">Search posts</button>`, body => { const go = () => { m().search = D.$('#threads-search', body).value; D.$('#system-dialog').close(); ctx.save(); render(); ctx.pane('primary'); }; D.$('#apply-thread-search', body).onclick = go; D.$('#threads-search', body).onkeydown = e => { if (e.key === 'Enter')
            go(); }; }));
        ctx.act('clear-search', () => { m().search = ''; ctx.save(); render(); });
        scope.on(root, 'input', e => { if (e.target.name === 'reply') {
            m().reply = e.target.value;
            ctx.save();
        } });
        scope.on(root, 'submit', e => { if (e.target.id === 'thread-reply') {
            e.preventDefault();
            const text = m().reply.trim();
            if (!text)
                return;
            selected().replies.push({ name: 'You', text });
            m().reply = '';
            ctx.save();
            render();
            const sc = D.$('.secondary-pane .scroll', root);
            sc.scrollTop = sc.scrollHeight;
        } });
        render();
        return { render };
    }));
})(window.Duo);
