(function(D){'use strict';
D.register({id:'tiktok',name:'TikTok',rank:4,pattern:'Film + conversation',description:'Watch original, locally playable films without covering them with comments. Swipe through the collection, save moments, and keep the conversation beside the video.',tip:'Unmute for the original ambient soundtrack. Swipe up or down on the film to change it; comments stay on their own surface.',boundary:'Three original 16-second films are bundled. Likes, follows, and comments are local; there is no TikTok feed or backend.'},ctx=>{
 const {root,scope}=ctx;const seed={index:0,tab:'foryou',liked:{},saved:{},following:{},comments:{dunes:[{name:'Noah Rivers',text:'A whole mood in sixteen seconds.'},{name:'Maya Torres',text:'That last ridge of light…'}],coast:[{name:'Sofia Chen',text:'This is the pace I needed today.'}],alpine:[{name:'Ari Lane',text:'A small reminder to look up.'}]},draft:'',muted:true,times:{}};let s=ctx.get(seed),video=null,wasPlaying=true;
 const clip=()=>D.clips[s.index%D.clips.length];
 function paintSide(){const c=clip(),comments=s.comments[c.id]||[];D.$('.tiktok-comments',root).innerHTML=`<div class="creator-card"><div class="row">${D.avatar(c.author)}<div class="grow"><b style="font-size:12px">${D.escape(c.author)}</b><p>Original landscape filmmaker · demo</p></div>${D.btn('follow',null,s.following[c.id]?'Following':'Follow','small')}</div><h2>${D.escape(c.short)}</h2><p>${D.escape(c.description)}</p></div><div class="tiktok-reply-count row"><b>${comments.length} local comments</b><span class="spacer"></span>${D.ib('share-video','share','Share this film')}</div><div class="scroll">${comments.map(c=>`<div class="reply">${D.avatar(c.name,'tiny')}<div><b>${D.escape(c.name)}</b><p>${D.escape(c.text)}</p></div></div>`).join('')||D.empty('comment','Start a little conversation','Your comment stays on this device.')}</div><form class="composer" data-form="comment"><div class="composer-box"><input name="comment" aria-label="Comment on film" placeholder="Say something kind…" maxlength="2000" value="${D.escape(s.draft)}"><button type="submit" class="send-btn" aria-label="Post comment locally">${D.icon('send',18)}</button></div></form>`;paintButtons();}
 function paintButtons(){const c=clip(),like=D.$('[data-action="like"]',root),save=D.$('[data-action="save"]',root);if(like){like.classList.toggle('liked',!!s.liked[c.id]);like.setAttribute('aria-pressed',String(!!s.liked[c.id]));like.innerHTML=D.icon('heart',27)+`<span>${s.liked[c.id]?'Liked':'Like'}</span>`;}if(save){save.classList.toggle('liked',!!s.saved[c.id]);save.setAttribute('aria-pressed',String(!!s.saved[c.id]));save.innerHTML=D.icon('bookmark',25)+`<span>${s.saved[c.id]?'Saved':'Save'}</span>`;}const mute=D.$('[data-action="mute"]',root);if(mute){mute.innerHTML=D.icon(s.muted?'mute':'volume',24)+`<span>${s.muted?'Sound on':'Mute'}</span>`;}const play=D.$('[data-action="play"]',root);if(play){play.innerHTML=D.icon(video?.paused?'play':'pause',23);play.setAttribute('aria-label',video?.paused?'Play film':'Pause film');}}
 function render(){s=ctx.get(seed);video?.pause();const c=clip();root.innerHTML=D.appHeader('tiktok','A wider view. A closer conversation.',`${D.ib('previous','up','Previous film')}${D.ib('next','down','Next film')}`)+D.paneTabs('Film','Conversation')+`<div class="duo-panes tiktok-panes"><section class="pane primary-pane tiktok-video-column"><div class="video-stage"><video playsinline loop preload="metadata" muted poster="${D.assets[c.id+'.jpg']}" aria-label="${D.escape(c.title)}"></video><div class="tiktok-top"><button data-action="collection" class="${s.tab==='saved'?'active':''}">Saved</button><button data-action="foryou" class="${s.tab==='foryou'?'active':''}">For you</button></div><div class="tiktok-title">${D.escape(c.id==='dunes'?'The quiet\nbetween.':c.id==='coast'?'Take the\nlong way.':'Above\nthe noise.').replace(/\n/g,'<br>')}</div><div class="tiktok-caption"><b>@${D.escape(c.author.toLowerCase().replaceAll(' ','.'))}</b><p>${D.escape(c.short)}</p><small>♫ Original ambient score · offline film</small></div><div class="tiktok-controls"><button data-action="like" aria-label="Like film"></button><button data-action="comments" aria-label="Open comments">${D.icon('comment',27)}<span>Discuss</span></button><button data-action="save" aria-label="Save film"></button><button data-action="share-video" aria-label="Share film">${D.icon('share',25)}<span>Share</span></button><button data-action="mute" aria-label="Toggle sound"></button><button data-action="play" aria-label="Play film"></button></div><input class="tiktok-timeline" type="range" min="0" max="16" step=".01" value="0" name="seek" aria-label="Film playback position"></div></section><section class="pane secondary-pane tiktok-comments"></section></div>`;
 video=D.$('video',root);video.src=D.assets[c.id+'.mp4'];video.muted=s.muted;video.volume=D.store.data.prefs.volume;video.onloadedmetadata=()=>{video.currentTime=D.clamp(s.times[c.id]||0,0,Math.max(0,video.duration-.1));D.$('[name="seek"]',root).max=video.duration||16;};video.ontimeupdate=()=>{const seek=D.$('[name="seek"]',root);if(seek)seek.value=video.currentTime;s.times[c.id]=video.currentTime;};video.onplay=paintButtons;video.onpause=paintButtons;video.onerror=()=>D.toast('This browser could not decode the bundled H.264 film. Try a modern browser.');paintSide();ctx.pane(root.dataset.activePane||'primary');video.play().catch(()=>paintButtons());}
 function next(delta){const saved=D.clips.map((c,i)=>s.saved[c.id]?i:-1).filter(i=>i>=0);if(s.tab==='saved'&&saved.length){const at=saved.indexOf(s.index);s.index=saved[(Math.max(at,0)+delta+saved.length)%saved.length];}else s.index=(s.index+delta+D.clips.length)%D.clips.length;ctx.save();render();}
 ctx.act('next',()=>next(1));ctx.act('previous',()=>next(-1));ctx.act('foryou',()=>{s.tab='foryou';ctx.save();render();});ctx.act('collection',()=>{const i=D.clips.findIndex(c=>s.saved[c.id]);if(i<0){D.toast('Save a film with the bookmark first');return;}s.tab='saved';s.index=i;ctx.save();render();});
 ctx.act('play',()=>video.paused?video.play().catch(()=>D.toast('Tap the film again to begin playback.')):video.pause());ctx.act('mute',()=>{s.muted=!s.muted;video.muted=s.muted;video.volume=Math.max(.1,D.store.data.prefs.volume);ctx.save();paintButtons();if(video.paused)video.play().catch(()=>{});});
 ctx.act('like',()=>{s.liked[clip().id]=!s.liked[clip().id];ctx.save();paintButtons();});ctx.act('save',()=>{s.saved[clip().id]=!s.saved[clip().id];ctx.save();paintButtons();});ctx.act('follow',()=>{s.following[clip().id]=!s.following[clip().id];ctx.save();paintSide();});ctx.act('comments',()=>{ctx.pane('secondary');D.$('[name="comment"]',root).focus();});
 ctx.act('share-video',()=>ctx.share(`${clip().title}\n\n${clip().description}\n\nAvailable in the Duo Studio offline film collection.`,clip().short));ctx.act('share-app',()=>ctx.actions['share-video']());
 scope.on(root,'input',e=>{if(e.target.name==='comment'){s.draft=e.target.value;ctx.save();}if(e.target.name==='seek'){video.currentTime=+e.target.value;}});scope.on(root,'submit',e=>{if(!e.target.matches('[data-form="comment"]'))return;e.preventDefault();const text=s.draft.trim();if(!text)return;(s.comments[clip().id]||=[]).push({name:'You',text});s.draft='';ctx.save();paintSide();D.$('.tiktok-comments .scroll',root).scrollTop=1e6;});
 let swipe=null;scope.on(root,'pointerdown',e=>{if(e.target.matches('video'))swipe={x:e.clientX,y:e.clientY};});scope.on(root,'pointerup',e=>{if(!swipe)return;const dy=e.clientY-swipe.y,dx=e.clientX-swipe.x;swipe=null;if(Math.abs(dy)>45&&Math.abs(dy)>Math.abs(dx)*1.3)next(dy<0?1:-1);else if(Math.abs(dy)<8&&Math.abs(dx)<8)ctx.actions.play();});scope.on(root,'pointercancel',()=>swipe=null);
 scope.on(document,'visibilitychange',()=>{if(document.hidden){wasPlaying=video&&!video.paused;video?.pause();}else if(root.isConnected&&!root.closest('.hidden')&&wasPlaying)video?.play().catch(()=>{});});
 render();return {render,suspend(){wasPlaying=video&&!video.paused;video?.pause();ctx.save();},resume(){if(wasPlaying)video?.play().catch(()=>{});},dispose(){video?.pause();if(video){video.removeAttribute('src');video.load();}}};
});})(window.Duo);
