(function(D){
'use strict';
D.scenes=[
 {id:'dunes',name:'The quiet between',creator:'Sofia Chen',handle:'sofia.studies',kind:'Landscape study',text:'Somewhere between the last light and the first stars. An original digital landscape, made for a slower moment.',palette:['#352143','#855061','#d1938e','#efc9ab']},
 {id:'coast',name:'Take the long way',creator:'Noah Rivers',handle:'noah.rivers',kind:'Coastal study',text:'Salt in the air. Nothing on the calendar. A shoreline imagined in color and contour.',palette:['#083e58','#29a49f','#89d0bb','#e4ce9b']},
 {id:'alpine',name:'Above the noise',creator:'Maya Torres',handle:'maya.outside',kind:'Alpine study',text:'Blue hour, a thousand stars, and room to breathe. Original generative mountain artwork.',palette:['#101c3b','#364f6e','#8ca5b7','#d7e0e7']},
 {id:'arches',name:'A study in light',creator:'Leo Park',handle:'leo.forms',kind:'Architecture study',text:'Repetition, rhythm, and a little afternoon sun. A fictional architectural space.',palette:['#635956','#aa9682','#d3c1a5','#ece0ca']},
 {id:'orbital',name:'Soft gravity',creator:'Ari Lane',handle:'ari.objects',kind:'Material study',text:'An orbital object caught in a soft, imaginary gravity. Made of light, not matter.',palette:['#151b30','#456982','#9baebb','#dfd8e5']},
 {id:'golden',name:'Golden, again',creator:'Sofia Chen',handle:'sofia.studies',kind:'Desert study',text:'Warm light. Long shadows. The landscape changes even when you stand still.',palette:['#384456','#967063','#d19d74','#f4cca0']},
];
D.clips=[
 {id:'dunes',title:'The quiet between · a 16-second landscape film',short:'Stay for the last light.',author:'Sofia Chen',views:'12.4K',description:'An original animated landscape study with a synthesized ambient score. This bundled demonstration film works entirely offline.',chapters:[['Opening light',0],['The ridge',5],['A softer horizon',10],['Last light',14]]},
 {id:'coast',title:'Take the long way · color, coast & calm',short:'Your sign to take the slow route.',author:'Noah Rivers',views:'8.2K',description:'A camera drift across an original procedural coastal illustration. All media in this prototype is bundled and locally playable.',chapters:[['Tide line',0],['Contours',4],['Across the bay',9],['The long way',13]]},
 {id:'alpine',title:'Above the noise · blue-hour mountain study',short:'Turn your volume up. Take a breath.',author:'Maya Torres',views:'21K',description:'An original night-sky and mountain illustration, animated as a quiet blue-hour film. Music is an original synthesized composition.',chapters:[['Nightfall',0],['A thousand stars',4],['Blue hour',8],['The summit',12]]},
];
D.documents=[
 {id:'travel',title:'A weekend with room to breathe',site:'Fieldnotes Journal',category:'Travel',image:'alpine',tags:'weekend mountains trip alps hiking getaway nature travel',summary:'A slower three-day itinerary: a lakeside morning, a ridge walk, and an unhurried Sunday.',body:['A weekend does not need to be a checklist. Start with one place, one good walk, and enough empty space to discover something along the way.','Friday: arrive before sunset, settle into a small guesthouse, and take a short walk along the water. Leave the first evening unplanned.','Saturday: begin early, take the scenic ridge path, and pack a simple lunch. This is a fictional itinerary for exploring the simulator, not real-world trail advice.','Sunday: coffee, a sketchbook, and the long way home. In Duo Studio you can send this page to ChatGPT to create a planning document, or to Gmail to write an invitation.']},
 {id:'design',title:'Beyond a bigger rectangle',site:'Form / Function',category:'Design',image:'orbital',tags:'design interface duo foldable ui ux screen adaptive layout',summary:'The best expanded-screen interfaces make two related tasks possible at the same time.',body:['More space is an opportunity to preserve context. A reader should not disappear when a search result opens. A conversation should not disappear when a document is edited.','Start with a primary surface and a complementary surface. Give each a clear job. Do not fill a second pane just because it exists.','At narrow widths, keep the same model and expose a compact pane switcher. When the viewport expands again, restore both surfaces without losing the user’s position.','A fold is a posture, not an instruction to split every app down the middle. The open screen can be one canvas.']},
 {id:'architecture',title:'The architecture of afternoon light',site:'Studio Assembly',category:'Architecture',image:'arches',tags:'architecture design arches buildings gallery art light concrete minimal',summary:'A visual essay in rhythm, repetition, material, and shadow.',body:['Light is the most changeable material in a room. The same repeated arch can feel warm, theatrical, or quiet depending on its shadow.','This original digital study is fictional. It uses a simple geometric scene to explore how repeated forms create depth.','Collect three colors, one material, and a sense of rhythm. Send this essay to Gemini to assemble a moodboard.']},
 {id:'coast',title:'A field guide to doing less',site:'Slow Atlas',category:'Travel',image:'coast',tags:'coast beach sea ocean holiday travel relaxing weekend',summary:'A coastal color story for people who want fewer plans and more horizon.',body:['There is a particular color where shallow water meets sand. It shifts from pale green to saturated teal with only a few steps.','This is an original imagined coastal scene. Its contour lines are generated mathematically, not taken from a real map.','Make a small collection: a color, a sentence, a moment. The purpose of this sample is to demonstrate search, reading, saving, and cross-app context sharing.']},
 {id:'gpu',title:'A little world, computed in parallel',site:'Compute Notebook',category:'Technology',image:'orbital',tags:'webgpu javascript gpu compute shader html technology graphics rendering',summary:'A procedural visual field becomes the backdrop to a semantic, accessible DOM interface.',body:['Duo Studio uses a compute shader to write a texture and a separate render pass to present it. The interface itself remains HTML.','Each invocation computes one pixel. Small workgroups cover the image. A uniform buffer supplies the viewport, time, palette, and pointer.','The fallback is a Canvas 2D renderer. The same apps remain functional when WebGPU is unavailable; only the decorative rendering path changes.']},
 {id:'color',title:'Five colors are enough',site:'Chromatic Notes',category:'Design',image:'dunes',tags:'color palette moodboard creative design sunset dunes gradient',summary:'A practical approach to making an atmosphere, not just a palette.',body:['Choose a dark anchor, a middle tone, a surface color, and one deliberate accent. Restraint makes the accent matter.','The desert study in this collection moves from a deep plum sky to pale, warm light. Each ridge repeats the palette with a slightly different value.','Try a visual brief in Gemini, then edit the board. The prototype is deterministic and uses local artwork, rather than a remote image model.']},
 {id:'focus',title:'A better kind of focus',site:'Everyday Systems',category:'Lifestyle',image:'golden',tags:'focus productivity planning work day study tips',summary:'Keep your reference in sight, and your next action within reach.',body:['Repeatedly switching applications has a practical cost: the reference you needed is no longer visible.','A side-by-side workspace can keep the source on one side and the work on the other. This is why Duo Studio supports saved app pairs.','Try Google plus ChatGPT for research, Maps plus WhatsApp for coordinating a route, or YouTube plus Gmail for taking notes and drafting a follow-up.']},
 {id:'offline',title:'Designing for the moment the network disappears',site:'Local First Lab',category:'Technology',image:'alpine',tags:'offline browser local storage prototype javascript performance apps data',summary:'A self-contained interface should still be useful without a server.',body:['All sample content, artwork, and films in Duo Studio are bundled. The standalone HTML performs no runtime network requests.','Local persistence is best effort. Browsers can deny storage or run out of quota. Export a session JSON file to create an explicit backup.','Uploads are resized before persistence. Native video playback uses local media; imported videos are session-only and are not copied into the JSON export.']},
];
D.seedMail=[
 {id:'m1',from:'Sofia Chen',email:'sofia@example.com',subject:'A few ideas for our next escape',preview:'A little coast, a little quiet, and no early alarms.',body:'Hey!\n\nI put together a few ideas for our next long weekend. Think quiet mornings, a short walk along the water, and a place with really good coffee.\n\nThere is a coastal study in the shared collection that feels exactly right. Take a look, and send me your favorite.\n\nShall we make some room for it?\n\nSofia',time:'9:24 AM',unread:true,star:true,folder:'inbox',art:'coast'},
 {id:'m2',from:'Studio Assembly',email:'hello@example.com',subject:'Your daily dose of a different perspective',preview:'Form, function, and a little afternoon light.',body:'Hello from the studio,\n\nThis week we are exploring the architecture of light. Six original digital studies are now part of your Duo collection.\n\nOpen Google and search “architecture” to see the complete essay.\n\nThe Assembly team',time:'8:51 AM',unread:true,star:false,folder:'inbox',art:'arches'},
 {id:'m3',from:'Noah Rivers',email:'noah@example.com',subject:'Sunday walk? I have a route.',preview:'A coffee stop is non-negotiable.',body:'Hey,\n\nWant to try the riverside loop on Sunday? I found a great route through the park in our fictional demo city, Porto Alba.\n\nLet’s meet at the little coffee place and see where the day takes us.\n\nNoah',time:'8:12 AM',unread:false,star:false,folder:'inbox'},
 {id:'m4',from:'Maya Torres',email:'maya@example.com',subject:'Blue-hour edit — ready for a look',preview:'The mountain sequence is finished.',body:'Hi!\n\nThe new blue-hour sequence is ready. It is in the YouTube collection, along with the dunes and coast films.\n\nI would love your thoughts on the opening and the final frame. You can take timestamped notes alongside the video.\n\nThanks,\nMaya',time:'Yesterday',unread:false,star:true,folder:'inbox',art:'alpine'},
 {id:'m5',from:'Leo Park',email:'leo@example.com',subject:'Re: Thursday design review',preview:'Keeping the reference visible makes a difference.',body:'Agreed. Let’s focus on the relationship between the two surfaces, rather than simply making the app wider.\n\nCan you bring the moodboard and a couple of sketches?\n\nLeo',time:'Yesterday',unread:false,star:false,folder:'inbox'},
 {id:'m6',from:'Duo Studio',email:'studio@example.com',subject:'Welcome to your new canvas',preview:'Ten familiar apps. A different kind of space.',body:'Welcome to Duo Studio.\n\nThis is an independent, offline form-factor prototype, not iOS or a connection to Gmail. Every message and conversation is local demonstration data.\n\nTry folding, rotating, opening a second app, and sending context from one side to the other. Your state stays with you.\n\nMake something lovely.',time:'Sep 19',unread:false,star:false,folder:'inbox'},
];
D.engine={
 rank(query,docs=D.documents){const tokens=String(query).toLowerCase().match(/[\p{L}\p{N}]+/gu)||[];const stop=new Set(['the','a','of','in','for','to','and']);const q=tokens.filter(t=>!stop.has(t));return docs.map(doc=>{let score=0;for(const token of q){score+=(doc.title.toLowerCase().includes(token)?5:0)+(doc.tags.includes(token)?3:0)+(doc.summary.toLowerCase().includes(token)?1:0);}return {doc,score};}).filter(x=>!q.length||x.score>0).sort((a,b)=>b.score-a.score).map(x=>x.doc);},
 classify(text){const t=text.toLowerCase();if(/code|html|javascript|component|webgpu|shader/.test(t))return 'code';if(/mail|email|invitation|reply|letter/.test(t))return 'email';if(/trip|weekend|coast|travel|mountain|route|plan/.test(t))return 'trip';if(/summari|summary|research|compare/.test(t))return 'summary';return 'brief';},
 generate(text,context=''){
 const type=this.classify(text);const clean=text.trim().slice(0,180);let title='A little more possibility',body='',reply='';
 if(type==='trip'){title='A slower kind of weekend';body=`# A slower kind of weekend\n\nBrief: ${clean}\n\n## Friday · Arrive slowly\nCheck in, settle in, and take a short walk before dinner. Keep the evening open.\n\n## Saturday · Follow your curiosity\nStart with coffee. Choose one outdoor activity and one place to stop. Leave room to change your mind.\n\n## Sunday · The long way home\nA relaxed breakfast, a few photographs, and an unhurried departure.\n\n## Before you go\n☐ Pick dates\n☐ Confirm transport and accommodation\n☐ Check local conditions\n☐ Share the plan\n\nThis is a fictional planning template, not verified travel advice.`;reply='I’ve put a flexible three-day plan on the canvas. Edit it while keeping our conversation in view, then share it with a friend.';}
 else if(type==='email'){title='An invitation worth sending';body=`Subject: A little time away?\n\nHey,\n\nI’ve been thinking about this: ${clean}\n\nLet’s keep it simple — one place, a little time to explore, and enough room to see what we find.\n\nWould you be up for making a plan together?\n\nLet me know what works for you.\n\nCheers`;reply='Your editable draft is on the right. You can refine it here, export it, or hand it to the Gmail prototype without retyping.';}
 else if(type==='code'){title='An adaptive two-pane component';body=`<!doctype html>\n<html lang="en">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<style>\n  * { box-sizing: border-box }\n  body { margin: 0; font: 16px system-ui; color: #20313e; background: #edf3ef }\n  main { display: grid; grid-template-columns: 1fr 1fr; gap: 18px; padding: 24px }\n  section { border-radius: 24px; background: white; padding: 28px; min-height: 220px }\n  h1 { font-size: 30px; letter-spacing: -.04em }\n  small { color: #39826c; letter-spacing: .15em }\n  @media(max-width: 520px) { main { grid-template-columns: 1fr } }\n</style>\n<main>\n  <section><small>01 · REFERENCE</small><h1>Keep the thought.</h1><p>One continuous canvas. Two related activities.</p></section>\n  <section><small>02 · CREATION</small><h1>Make the next move.</h1><p>Your context stays in view while you work.</p></section>\n</main>\n</html>`;reply='I’ve loaded a working HTML/CSS two-pane example. Edit the code, then use Preview to render it in a network-isolated sandbox. This is a local template, not a remote model response.';}
 else if(type==='summary'){title='Notes & next steps';const src=context||clean;body=`# Notes & next steps\n\n## Source excerpt\n${src.slice(0,2500)}\n\n## Working structure\n1. Identify the central question.\n2. Keep the original reference beside the draft.\n3. Separate confirmed facts from assumptions.\n4. Turn the useful observations into one concrete next step.\n\n## Your notes\nAdd your conclusions here.\n\nThis template organizes supplied text; it is not an AI-generated factual summary.`;reply='The source text is pinned beside a structured notes template. Keep the original in view as you write your conclusions.';}
 else{title='From thought to something tangible';body=`# ${clean||'A new idea'}\n\n## The intention\nWhat should this feel like? What should it help someone do?\n\n## The essentials\n• One clear primary task\n• A supporting surface that preserves context\n• A thoughtful compact layout\n• An obvious next action\n\n## A first direction\nStart small, make the central interaction work, then refine the details.\n\n## Next steps\n☐ Write the first draft\n☐ Test the interaction\n☐ Share it for feedback`;reply='I’ve opened a working brief on the canvas. It’s a starting structure you can edit, rather than a claim of live AI generation.';}
 return {type,title,body,reply};
 },
 shortestPath(graph,start,goal){const costs=new Map([[start,0]]),previous=new Map(),open=new Set([start]);while(open.size){let u=null;for(const id of open)if(u===null||costs.get(id)<costs.get(u))u=id;if(u===goal){const path=[];for(let x=u;x!==undefined;x=previous.get(x))path.unshift(x);return {path,cost:costs.get(u)};}open.delete(u);for(const edge of graph[u]?.edges||[]){const c=costs.get(u)+edge.cost;if(c<(costs.get(edge.to)??Infinity)){costs.set(edge.to,c);previous.set(edge.to,u);open.add(edge.to);}}}return {path:[],cost:Infinity};},
};
})(window.Duo);
